=== threatsource2023Sec/weblogic/org.opensaml.opensaml-core.jar/schema/xmltooling-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xt="http://www.opensaml.org/xmltooling-config" targetNamespace="http://www.opensaml.org/xmltooling-config">

    <element name="XMLTooling" type="xt:XMLToolingType"/>
    <complexType name="XMLToolingType">
        <sequence>
            <element ref="xt:ObjectProviders" minOccurs="0"/>
            <element ref="xt:IDAttributes" minOccurs="0"/>
        </sequence>
    </complexType>

    <element name="ObjectProviders" type="xt:ObjectProvidersType"/>
    <complexType name="ObjectProvidersType">
        <sequence>
            <element ref="xt:ObjectProvider" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <element name="ObjectProvider" type="xt:ObjectProviderType"/>
    <complexType name="ObjectProviderType">
        <sequence>
            <element ref="xt:BuilderClass"/>
            <element ref="xt:MarshallingClass"/>
            <element ref="xt:UnmarshallingClass"/>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>

        <attribute name="qualifiedName" type="QName" use="required"/>
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>

    <element name="BuilderClass" type="xt:ClassType"/>
    <element name="MarshallingClass" type="xt:ClassType"/>
    <element name="UnmarshallingClass" type="xt:ClassType"/>
    <complexType name="ClassType">
        <sequence>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>

        <attribute name="className" type="string" use="required"/>
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>

    <element name="IDAttributes" type="xt:IDAttributesType"/>
    <complexType name="IDAttributesType">
        <sequence>
            <element ref="xt:IDAttribute" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <element name="IDAttribute" type="QName"/>
</schema>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-saml-impl.jar/saml-ec-gss-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:samlec="urn:ietf:params:xml:ns:samlec" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">
 
    <!-- SAML-EC GSS-API Object providers -->
    <ObjectProviders>
        
        <!-- EncType -->
        <ObjectProvider qualifiedName="samlec:EncType">
            <BuilderClass className="org.opensaml.saml.ext.samlec.impl.EncTypeBuilder"/>
			<MarshallingClass className="org.opensaml.core.xml.schema.impl.XSStringMarshaller"/>
			<UnmarshallingClass className="org.opensaml.core.xml.schema.impl.XSStringUnmarshaller"/>
        </ObjectProvider>

        <!-- GeneratedKey -->
        <ObjectProvider qualifiedName="samlec:GeneratedKey">
            <BuilderClass className="org.opensaml.saml.ext.samlec.impl.GeneratedKeyBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.samlec.impl.GeneratedKeyMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.samlec.impl.GeneratedKeyUnmarshaller"/>
        </ObjectProvider>

        <ObjectProvider qualifiedName="samlec:GeneratedKeyType">
            <BuilderClass className="org.opensaml.saml.ext.samlec.impl.GeneratedKeyBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.samlec.impl.GeneratedKeyMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.samlec.impl.GeneratedKeyUnmarshaller"/>
        </ObjectProvider>

        <!-- SessionKey -->
        <ObjectProvider qualifiedName="samlec:SessionKey">
            <BuilderClass className="org.opensaml.saml.ext.samlec.impl.SessionKeyBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.samlec.impl.SessionKeyMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.samlec.impl.SessionKeyUnmarshaller"/>
        </ObjectProvider>

        <ObjectProvider qualifiedName="samlec:SessionKeyType">
            <BuilderClass className="org.opensaml.saml.ext.samlec.impl.SessionKeyBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.samlec.impl.SessionKeyMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.samlec.impl.SessionKeyUnmarshaller"/>
        </ObjectProvider>

    </ObjectProviders>
 </XMLTooling>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-soap-impl.jar/wspolicy-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

    <!-- WS-Policy 2004 Object Providers -->
    <ObjectProviders>
    
        <!-- wsp:All -->
        <ObjectProvider qualifiedName="wsp:All">
            <BuilderClass className="org.opensaml.soap.wspolicy.impl.AllBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wspolicy.impl.AllMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wspolicy.impl.AllUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsp:AppliesTo -->
        <ObjectProvider qualifiedName="wsp:AppliesTo">
            <BuilderClass className="org.opensaml.soap.wspolicy.impl.AppliesToBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wspolicy.impl.AppliesToMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wspolicy.impl.AppliesToUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsp:ExactlyOne -->
        <ObjectProvider qualifiedName="wsp:ExactlyOne">
            <BuilderClass className="org.opensaml.soap.wspolicy.impl.ExactlyOneBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wspolicy.impl.ExactlyOneMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wspolicy.impl.ExactlyOneUnmarshaller"/>
        </ObjectProvider>

        <!-- wsp:Policy -->
        <ObjectProvider qualifiedName="wsp:Policy">
            <BuilderClass className="org.opensaml.soap.wspolicy.impl.PolicyBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wspolicy.impl.PolicyMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wspolicy.impl.PolicyUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsp:PolicyAttachment -->
        <ObjectProvider qualifiedName="wsp:PolicyAttachment">
            <BuilderClass className="org.opensaml.soap.wspolicy.impl.PolicyAttachmentBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wspolicy.impl.PolicyAttachmentMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wspolicy.impl.PolicyAttachmentUnmarshaller"/>
        </ObjectProvider>

        <!-- wsp:PolicyReference -->
        <ObjectProvider qualifiedName="wsp:PolicyReference">
            <BuilderClass className="org.opensaml.soap.wspolicy.impl.PolicyReferenceBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wspolicy.impl.PolicyReferenceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wspolicy.impl.PolicyReferenceUnmarshaller"/>
        </ObjectProvider>

    </ObjectProviders>

</XMLTooling>
