=== threatsource2023Sec/weblogic/org.opensaml.opensaml-core.jar/schema/xmltooling-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xt="http://www.opensaml.org/xmltooling-config" targetNamespace="http://www.opensaml.org/xmltooling-config">

    <element name="XMLTooling" type="xt:XMLToolingType"/>
    <complexType name="XMLToolingType">
        <sequence>
            <element ref="xt:ObjectProviders" minOccurs="0"/>
            <element ref="xt:IDAttributes" minOccurs="0"/>
        </sequence>
    </complexType>

    <element name="ObjectProviders" type="xt:ObjectProvidersType"/>
    <complexType name="ObjectProvidersType">
        <sequence>
            <element ref="xt:ObjectProvider" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <element name="ObjectProvider" type="xt:ObjectProviderType"/>
    <complexType name="ObjectProviderType">
        <sequence>
            <element ref="xt:BuilderClass"/>
            <element ref="xt:MarshallingClass"/>
            <element ref="xt:UnmarshallingClass"/>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>

        <attribute name="qualifiedName" type="QName" use="required"/>
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>

    <element name="BuilderClass" type="xt:ClassType"/>
    <element name="MarshallingClass" type="xt:ClassType"/>
    <element name="UnmarshallingClass" type="xt:ClassType"/>
    <complexType name="ClassType">
        <sequence>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
        </sequence>

        <attribute name="className" type="string" use="required"/>
        <anyAttribute namespace="##other" processContents="lax"/>
    </complexType>

    <element name="IDAttributes" type="xt:IDAttributesType"/>
    <complexType name="IDAttributesType">
        <sequence>
            <element ref="xt:IDAttribute" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <element name="IDAttribute" type="QName"/>
</schema>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-soap-impl.jar/soap11-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<xt:XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xt="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">
    
    <!-- SOAP 1.1 Object Providers -->
    <xt:ObjectProviders>
    
        <!-- Body -->
        <xt:ObjectProvider qualifiedName="soap11:Body">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.BodyBuilder"/>
            <xt:MarshallingClass className="org.opensaml.soap.soap11.impl.BodyMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.soap.soap11.impl.BodyUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- Detail -->
        <xt:ObjectProvider qualifiedName="detail">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.DetailBuilder"/>
            <xt:MarshallingClass className="org.opensaml.soap.soap11.impl.DetailMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.soap.soap11.impl.DetailUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- Envelope -->
        <xt:ObjectProvider qualifiedName="soap11:Envelope">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.EnvelopeBuilder"/>
            <xt:MarshallingClass className="org.opensaml.soap.soap11.impl.EnvelopeMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.soap.soap11.impl.EnvelopeUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- Fault -->
        <xt:ObjectProvider qualifiedName="soap11:Fault">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.FaultBuilder"/>
            <xt:MarshallingClass className="org.opensaml.soap.soap11.impl.FaultMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.soap.soap11.impl.FaultUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- faultcode -->
        <xt:ObjectProvider qualifiedName="faultactor">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.FaultActorBuilder"/>
            <xt:MarshallingClass className="org.opensaml.core.xml.schema.impl.XSURIMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.core.xml.schema.impl.XSURIUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- faultcode -->
        <xt:ObjectProvider qualifiedName="faultcode">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.FaultCodeBuilder"/>
            <xt:MarshallingClass className="org.opensaml.core.xml.schema.impl.XSQNameMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.core.xml.schema.impl.XSQNameUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- faultstring -->
        <xt:ObjectProvider qualifiedName="faultstring">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.FaultStringBuilder"/>
            <xt:MarshallingClass className="org.opensaml.core.xml.schema.impl.XSStringMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.core.xml.schema.impl.XSStringUnmarshaller"/>
        </xt:ObjectProvider>
        
        <!-- Header -->
        <xt:ObjectProvider qualifiedName="soap11:Header">
            <xt:BuilderClass className="org.opensaml.soap.soap11.impl.HeaderBuilder"/>
            <xt:MarshallingClass className="org.opensaml.soap.soap11.impl.HeaderMarshaller"/>
            <xt:UnmarshallingClass className="org.opensaml.soap.soap11.impl.HeaderUnmarshaller"/>
        </xt:ObjectProvider>
        
    </xt:ObjectProviders>

</xt:XMLTooling>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-soap-impl.jar/wsaddressing-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

    <!-- WS-Addressing 1.0 Object Providers -->
    <ObjectProviders>
    
        <!-- wsa:Action -->
        <ObjectProvider qualifiedName="wsa:Action">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ActionBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ActionMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ActionUnmarshaller"/>
        </ObjectProvider>

        <!-- wsa:Address -->
        <ObjectProvider qualifiedName="wsa:Address">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.AddressBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.AddressMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.AddressUnmarshaller"/>
        </ObjectProvider>

        <!-- wsa:EndpointReference -->
        <ObjectProvider qualifiedName="wsa:EndpointReference">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.EndpointReferenceBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.EndpointReferenceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.EndpointReferenceUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:FaultTo -->
        <ObjectProvider qualifiedName="wsa:FaultTo">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.FaultToBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.FaultToMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.FaultToUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:From -->
        <ObjectProvider qualifiedName="wsa:From">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.FromBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.FromMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.FromUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:MessageID -->
        <ObjectProvider qualifiedName="wsa:MessageID">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.MessageIDBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.MessageIDMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.MessageIDUnmarshaller"/>
        </ObjectProvider>

        <!-- wsa:Metadata -->
        <ObjectProvider qualifiedName="wsa:Metadata">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.MetadataBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.MetadataMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.MetadataUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:ProblemAction -->
        <ObjectProvider qualifiedName="wsa:ProblemAction">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ProblemActionBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ProblemActionMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ProblemActionUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:ProblemHeaderQName -->
        <ObjectProvider qualifiedName="wsa:ProblemHeaderQName">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ProblemHeaderQNameBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ProblemHeaderQNameMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ProblemHeaderQNameUnmarshaller"/>
        </ObjectProvider>

        <!-- wsa:ProblemIRI -->
        <ObjectProvider qualifiedName="wsa:ProblemIRI">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ProblemIRIBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ProblemIRIMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ProblemIRIUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:ReferenceParameters -->
        <ObjectProvider qualifiedName="wsa:ReferenceParameters">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ReferenceParametersBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ReferenceParametersMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ReferenceParametersUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:RelatesTo -->
        <ObjectProvider qualifiedName="wsa:RelatesTo">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.RelatesToBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.RelatesToMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.RelatesToUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:ReplyTo -->
        <ObjectProvider qualifiedName="wsa:ReplyTo">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ReplyToBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ReplyToMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ReplyToUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:RetryAfter -->
        <ObjectProvider qualifiedName="wsa:RetryAfter">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.RetryAfterBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.RetryAfterMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.RetryAfterUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsa:SoapAction -->
        <ObjectProvider qualifiedName="wsa:SoapAction">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.SoapActionBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.SoapActionMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.SoapActionUnmarshaller"/>
        </ObjectProvider>

        <!-- wsa:To -->
        <ObjectProvider qualifiedName="wsa:To">
            <BuilderClass className="org.opensaml.soap.wsaddressing.impl.ToBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wsaddressing.impl.ToMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wsaddressing.impl.ToUnmarshaller"/>
        </ObjectProvider>
        

    </ObjectProviders>

</XMLTooling>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-saml-impl.jar/saml2-metadata-algorithm-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns="http://www.opensaml.org/xmltooling-config" xmlns:alg="urn:oasis:names:tc:SAML:metadata:algsupport" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

    <!-- SAML v2.0 Metadata Profile for Algorithm Support Version 1.0 XMLObject providers -->
    <ObjectProviders>

        <!-- DigestMethod provider -->
        <ObjectProvider qualifiedName="alg:DigestMethod">
            <BuilderClass className="org.opensaml.saml.ext.saml2alg.impl.DigestMethodBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.DigestMethodMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.DigestMethodUnmarshaller"/>
        </ObjectProvider>

        <ObjectProvider qualifiedName="alg:DigestMethodType">
            <BuilderClass className="org.opensaml.saml.ext.saml2alg.impl.DigestMethodBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.DigestMethodMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.DigestMethodUnmarshaller"/>
        </ObjectProvider>
        
        <!-- SigningMethod provider -->
        <ObjectProvider qualifiedName="alg:SigningMethod">
            <BuilderClass className="org.opensaml.saml.ext.saml2alg.impl.SigningMethodBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.SigningMethodMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.SigningMethodUnmarshaller"/>
        </ObjectProvider>

        <ObjectProvider qualifiedName="alg:SigningMethodType">
            <BuilderClass className="org.opensaml.saml.ext.saml2alg.impl.SigningMethodBuilder"/>
            <MarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.SigningMethodMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml.ext.saml2alg.impl.SigningMethodUnmarshaller"/>
        </ObjectProvider>

    </ObjectProviders>
</XMLTooling>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-soap-impl.jar/wssecurity-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsse11="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

    <!-- WS-Security 2004 Object Providers -->
    <ObjectProviders>
    
        <!-- wsse:BinarySecurityToken -->
        <ObjectProvider qualifiedName="wsse:BinarySecurityToken">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.BinarySecurityTokenBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.BinarySecurityTokenMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.BinarySecurityTokenUnmarshaller"/>
        </ObjectProvider>

        <!-- wsu:Created -->
        <ObjectProvider qualifiedName="wsu:Created">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.CreatedBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.CreatedMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.CreatedUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Embedded -->
        <ObjectProvider qualifiedName="wsse:Embedded">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.EmbeddedBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.EmbeddedMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.EmbeddedUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse11:EncryptedHeader -->
        <ObjectProvider qualifiedName="wsse11:EncryptedHeader">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.EncryptedHeaderBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.EncryptedHeaderMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.EncryptedHeaderUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsu:Expires -->
        <ObjectProvider qualifiedName="wsu:Expires">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.ExpiresBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.ExpiresMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.ExpiresUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse11:Iteration -->
        <ObjectProvider qualifiedName="wsse11:Iteration">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.IterationBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.IterationMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.IterationUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:KeyIdentifier -->
        <ObjectProvider qualifiedName="wsse:KeyIdentifier">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.KeyIdentifierBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.KeyIdentifierMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.KeyIdentifierUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Nonce -->
        <ObjectProvider qualifiedName="wsse:Nonce">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.NonceBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.NonceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.NonceUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Password -->
        <ObjectProvider qualifiedName="wsse:Password">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.PasswordBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.PasswordMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.PasswordUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Reference -->
        <ObjectProvider qualifiedName="wsse:Reference">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.ReferenceBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.ReferenceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.ReferenceUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse11:Salt -->
        <ObjectProvider qualifiedName="wsse11:Salt">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.SaltBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.SaltMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.SaltUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Security -->
        <ObjectProvider qualifiedName="wsse:Security">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.SecurityBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.SecurityMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.SecurityUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:SecurityTokenReference -->
        <ObjectProvider qualifiedName="wsse:SecurityTokenReference">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.SecurityTokenReferenceBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.SecurityTokenReferenceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.SecurityTokenReferenceUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsu:SignatureConfirmation -->
        <ObjectProvider qualifiedName="wsu:SignatureConfirmation">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.SignatureConfirmationBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.SignatureConfirmationMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.SignatureConfirmationUnmarshaller"/>
        </ObjectProvider>

        <!-- wsu:Timestamp -->
        <ObjectProvider qualifiedName="wsu:Timestamp">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.TimestampBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.TimestampMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.TimestampUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsse:TransformationParameters -->
        <ObjectProvider qualifiedName="wsse:TransformationParameters">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.TransformationParametersBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.TransformationParametersMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.TransformationParametersUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsse:Username -->
        <ObjectProvider qualifiedName="wsse:Username">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.UsernameBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.UsernameMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.UsernameUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:UsernameToken -->
        <ObjectProvider qualifiedName="wsse:UsernameToken">
            <BuilderClass className="org.opensaml.soap.wssecurity.impl.UsernameTokenBuilder"/>
            <MarshallingClass className="org.opensaml.soap.wssecurity.impl.UsernameTokenMarshaller"/>
            <UnmarshallingClass className="org.opensaml.soap.wssecurity.impl.UsernameTokenUnmarshaller"/>
        </ObjectProvider>

    </ObjectProviders>
    
    <IDAttributes>
        <IDAttribute>wsu:Id</IDAttribute>
    </IDAttributes>

</XMLTooling>

=== threatsource2023Sec/weblogic/org.opensaml.opensaml-saml-impl.jar/saml2-metadata-rpi-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:mdrpi="urn:oasis:names:tc:SAML:metadata:rpi" xmlns="http://www.opensaml.org/xmltooling-config"
            xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

  <!-- SAML 2.0 Protocol IdP Discovery Protocol Object providers -->
  <ObjectProviders>

    <!-- Publication provider -->
    <ObjectProvider qualifiedName="mdrpi:Publication">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationUnmarshaller" />
    </ObjectProvider>
 
     <ObjectProvider qualifiedName="mdrpi:PublicationType">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationUnmarshaller" />
    </ObjectProvider>

   <!-- PublicationInfo provider -->
    <ObjectProvider qualifiedName="mdrpi:PublicationInfo">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationInfoBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationInfoMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationInfoUnmarshaller" />
    </ObjectProvider>

    <ObjectProvider qualifiedName="mdrpi:PublicationInfoType">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationInfoBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationInfoMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationInfoUnmarshaller" />
    </ObjectProvider>

    <!-- PublicationPath provider -->
    <ObjectProvider qualifiedName="mdrpi:PublicationPath">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationPathBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationPathMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationPathUnmarshaller" />
    </ObjectProvider>

    <ObjectProvider qualifiedName="mdrpi:PublicationPathType">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationPathBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationPathMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.PublicationPathUnmarshaller" />
    </ObjectProvider>

    <!-- UsagePolicy provider -->
    <ObjectProvider qualifiedName="mdrpi:UsagePolicy">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.UsagePolicyBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.UsagePolicyMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.UsagePolicyUnmarshaller" />
    </ObjectProvider>

    <!-- RegistrationPolicy provider -->
    <ObjectProvider qualifiedName="mdrpi:RegistrationPolicy">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationPolicyBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationPolicyMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationPolicyUnmarshaller" />
    </ObjectProvider>

    <!-- RegistrationInfo provider -->
    <ObjectProvider qualifiedName="mdrpi:RegistrationInfo">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationInfoBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationInfoMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationInfoUnmarshaller" />
    </ObjectProvider>

    <ObjectProvider qualifiedName="mdrpi:RegistrationInfoType">
      <BuilderClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationInfoBuilder" />
      <MarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationInfoMarshaller" />
      <UnmarshallingClass className="org.opensaml.saml.ext.saml2mdrpi.impl.RegistrationInfoUnmarshaller" />
    </ObjectProvider>

  </ObjectProviders>
</XMLTooling>
