=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/dtd/snmpMetadata.dtd
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!-- Copyright (c) Monfox, LLC 1999-2003. All Rights Reserved.     -->
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!ELEMENT SnmpMetadata (Module|ModuleRef)*>
<!ATTLIST SnmpMetadata name CDATA "MIB-DATA">

<!ELEMENT Module (Requires?, (ModuleIdentity?|Oid?|Object?|Table?|Notification?|ObjectGroup?|NotificationGroup?|Trap?|Type?|AgentCapabilities?|ModuleCompliance)*)>
<!ATTLIST Module name CDATA "DEFAULT">

<!ELEMENT Requires (ModuleRef*)>

<!ELEMENT ModuleList (ModuleRef*)>

<!ELEMENT ModuleRef EMPTY>
<!ATTLIST ModuleRef name CDATA #REQUIRED>

<!ELEMENT ModuleIdentity (Organization?, ContactInfo?, Description?)>
<!ATTLIST ModuleIdentity name        CDATA #REQUIRED
                         oid         CDATA #REQUIRED
			 lastUpdated CDATA #IMPLIED>

<!ELEMENT Organization (#PCDATA)>
<!ELEMENT Description  (#PCDATA)>
<!ELEMENT ContactInfo  (#PCDATA)>

<!ELEMENT Oid EMPTY>
<!ATTLIST Oid name CDATA #REQUIRED
              oid  CDATA #REQUIRED
	      rawValue CDATA #IMPLIED    
	      >
<!-- NOTE: 'rawValue' used in richMode only -->

<!ELEMENT Table (Entry,Description?)>
<!ATTLIST Table name    CDATA #REQUIRED
                oid     CDATA #REQUIRED
		status ( mandatory|current|obsolete
		        |deprecated|optional) "current">

<!ELEMENT Entry ((Indexes|Augments)?,Column+,Description?)>
<!ATTLIST Entry name   CDATA   #REQUIRED
                oid    CDATA   #REQUIRED
		status ( mandatory|current|obsolete
		        |deprecated|optional) "current">

<!ELEMENT Column EMPTY >
<!ATTLIST Column name    CDATA #REQUIRED
                 column  CDATA #REQUIRED
                 objtype (ip|i|g|c|c64|op|o|t|s|n) #REQUIRED>

<!ELEMENT Indexes (ObjectRef*) >
<!ELEMENT Augments (ObjectRef) >

<!ELEMENT Object ( (NamedNumberList?|Size?|RangeSpec?),Description?) >
<!ATTLIST Object  
	  name CDATA #REQUIRED
	  oid  CDATA #REQUIRED
	  objtype (ip|i|g|c|c64|op|o|t|s|n|entry) #REQUIRED
	  smitype (s|i|i32|u32|c|c32|c64|g|g32|ip|t|op|o|b|entry) #REQUIRED
	  access (ro|rw|wo|rc|na|no|ni) #REQUIRED
	  typeref CDATA #IMPLIED
	  status ( mandatory|current|obsolete|deprecated|optional) "current"
	  defval CDATA #IMPLIED
	  form   (entry|column|scalar) #IMPLIED
	  >

<!ELEMENT ObjectRef EMPTY>
<!ATTLIST ObjectRef 
          name     CDATA #REQUIRED
          modifier (implied) #IMPLIED
	  oid      CDATA #IMPLIED                           
	  objtype  (ip|i|g|c|c64|op|o|t|s|n|entry) #IMPLIED 
	  smitype  (s|i|i32|u32|c|c32|c64|
	            g|g32|ip|t|op|o|b|entry) #IMPLIED
	  >

<!-- NOTE: 'oid' used in richMode only -->
<!-- NOTE: 'objtype' used in richMode only -->
<!-- NOTE: 'smitype' used in richMode only -->

<!ELEMENT Objects (ObjectRef*)>

<!ELEMENT ObjectGroup (Objects,Description?)>
<!ATTLIST ObjectGroup name   CDATA #REQUIRED
                      oid    CDATA #REQUIRED
		      status ( mandatory|current|obsolete
			      |deprecated|optional) "current">

<!ELEMENT Trap (Variables,Description?)>
<!ATTLIST Trap name CDATA #REQUIRED
               enterprise     CDATA #REQUIRED
               oid            CDATA #IMPLIED
	       id             CDATA #REQUIRED
	       status        (  mandatory|current|obsolete
			       |deprecated|optional) "current">
<!ELEMENT Variables (ObjectRef*)>

<!ELEMENT Notification (Objects,Description?)>
<!ATTLIST Notification name   CDATA #REQUIRED
                       oid    CDATA #REQUIRED
		       status ( mandatory|current|obsolete
			       |deprecated|optional) "current">


<!ELEMENT NotificationRef EMPTY>
<!ATTLIST NotificationRef name CDATA #REQUIRED
                          oid    CDATA #IMPLIED
			  >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT Notifications (NotificationRef*)>

<!ELEMENT NotificationGroup (Notifications,Description?) >
<!ATTLIST NotificationGroup name   CDATA #REQUIRED
                            oid    CDATA #REQUIRED
			    status ( mandatory|current|obsolete
	                            |deprecated|optional) "current">

<!ELEMENT Type ( (NamedNumberList?|Size?|RangeSpec?),Description?) >
<!ATTLIST Type name        CDATA #IMPLIED
               type        CDATA #REQUIRED
	       objtype     (ip|i|g|c|c64|op|o|t|s|n|entry) #REQUIRED
               typeref     CDATA #IMPLIED
	       displayHint CDATA #IMPLIED
               status      ( mandatory|current|obsolete
	                    |deprecated|optional) "current" 
	       >

<!ELEMENT Size (RangeSpec)>

<!ELEMENT RangeSpec (RangeItem)*>

<!ELEMENT RangeItem EMPTY>
<!ATTLIST RangeItem  single CDATA #IMPLIED
                     lower  CDATA #IMPLIED
                     upper  CDATA #IMPLIED>

<!ELEMENT NamedNumberList (nn*) >

<!ELEMENT nn EMPTY >
<!ATTLIST nn name   CDATA #REQUIRED
             value  CDATA #REQUIRED>

<!ELEMENT AgentCapabilities (ProductRelease?,Description?,Reference?,Supports*)>
<!ATTLIST AgentCapabilities name CDATA #REQUIRED
			    oid  CDATA #REQUIRED
			    status      ( mandatory|current|obsolete
					 |deprecated|optional) "current">

<!ELEMENT ProductRelease  (#PCDATA)>
<!ELEMENT Reference  (#PCDATA)>

<!ELEMENT Supports  (Includes?,Variation*)>
<!ATTLIST Supports  module CDATA #REQUIRED>

<!ELEMENT Includes  (GroupRef*)>

<!ELEMENT GroupRef EMPTY>
<!ATTLIST GroupRef name CDATA #REQUIRED
                   oid  CDATA #IMPLIED
		   >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT Variation  (Syntax?,WriteSyntax?,CreationRequires?, Description?)>
<!ATTLIST Variation  name CDATA #REQUIRED
                     oid  CDATA #REQUIRED
                     access  CDATA #IMPLIED
                     defval  CDATA #IMPLIED>

<!ELEMENT ModuleCompliance (Description?,Reference?,McModule*)>
<!ATTLIST ModuleCompliance name CDATA #REQUIRED
		           oid  CDATA #REQUIRED
		           status      ( mandatory|current|obsolete
					 |deprecated|optional) "current">

<!ELEMENT McModule (MandatoryGroups?,(McGroup?|McObject?)*)>
<!ATTLIST McModule module CDATA #IMPLIED>

<!ELEMENT MandatoryGroups (GroupRef*)>

<!ELEMENT McGroup (Description?)>
<!ATTLIST McGroup name CDATA #REQUIRED
                  oid  CDATA #IMPLIED
		  >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT McObject (Syntax?,WriteSyntax?,Description?)>
<!ATTLIST McObject  name CDATA #REQUIRED
                    oid  CDATA #REQUIRED
                    access  CDATA #IMPLIED>
                           

<!ELEMENT Syntax (Type)>
<!ELEMENT WriteSyntax (Type)>
<!ELEMENT CreationRequires (ObjectRef*)>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMP-PROXY-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMP-PROXY-MIB">
   <Requires>
      <ModuleRef name="SNMP-FRAMEWORK-MIB" />
      <ModuleRef name="SNMP-TARGET-MIB" />
      <ModuleRef name="SNMPv2-TC" />
   </Requires>
   <ModuleIdentity name="snmpProxyMIB" oid="1.3.6.1.6.3.14" lastUpdated="9808040000Z">
      <Organization>IETF SNMPv3 Working Group</Organization>
      <ContactInfo>WG-email:   snmpv3@lists.tislabs.com
Subscribe:  majordomo@lists.tislabs.com
            In message body:  subscribe snmpv3

Chair:      Russ Mundy
            Trusted Information Systems
Postal:     3060 Washington Rd
            Glenwood MD 21738
            USA
EMail:      mundy@tislabs.com
Phone:      +1-301-854-6889

Co-editor:  David B. Levi
            SNMP Research, Inc.
Postal:     3001 Kimberlin Heights Road
            Knoxville, TN 37920-9716
EMail:      levi@snmp.com
Phone:      +1 423 573 1434

Co-editor:  Paul Meyer
            Secure Computing Corporation
Postal:     2675 Long Lake Road
            Roseville, MN 55113
EMail:      paul_meyer@securecomputing.com
Phone:      +1 651 628 1592

Co-editor:  Bob Stewart
            Cisco Systems, Inc.
Postal:     170 West Tasman Drive
            San Jose, CA 95134-1706
EMail:      bstewart@cisco.com
Phone:      +1 603 654 2686</ContactInfo>
      <Description>This MIB module defines MIB objects which provide
mechanisms to remotely configure the parameters
used by a proxy forwarding application.</Description>
   </ModuleIdentity>
   <Oid name="snmpProxyObjects" oid="1.3.6.1.6.3.14.1" />
   <Oid name="snmpProxyConformance" oid="1.3.6.1.6.3.14.3" />
   <Table name="snmpProxyTable" oid="1.3.6.1.6.3.14.1.2" status="current">
      <Entry name="snmpProxyEntry" oid="1.3.6.1.6.3.14.1.2.1" status="current">
         <Indexes>
            <ObjectRef name="snmpProxyName" modifier="implied" />
         </Indexes>
         <Column name="snmpProxyName" column="1" objtype="s" />
         <Column name="snmpProxyType" column="2" objtype="i" />
         <Column name="snmpProxyContextEngineID" column="3" objtype="s" />
         <Column name="snmpProxyContextName" column="4" objtype="s" />
         <Column name="snmpProxyTargetParamsIn" column="5" objtype="s" />
         <Column name="snmpProxySingleTargetOut" column="6" objtype="s" />
         <Column name="snmpProxyMultipleTargetOut" column="7" objtype="s" />
         <Column name="snmpProxyStorageType" column="8" objtype="i" />
         <Column name="snmpProxyRowStatus" column="9" objtype="i" />
      </Entry>
   </Table>
   <Object name="snmpProxyEntry" oid="1.3.6.1.6.3.14.1.2.1" objtype="entry" smitype="entry" access="na" typeref="SNMP-PROXY-MIB:SnmpProxyEntry" form="entry" status="current" />
   <Type name="SnmpProxyEntry" type="SEQUENCE" objtype="entry" />
   <Object name="snmpProxyName" oid="1.3.6.1.6.3.14.1.2.1.1" objtype="s" smitype="s" access="na" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="1" upper="32" />
         </RangeSpec>
      </Size>
   </Object>
   <Object name="snmpProxyType" oid="1.3.6.1.6.3.14.1.2.1.2" objtype="i" smitype="i" access="rc" form="column" status="current">
      <NamedNumberList>
         <nn name="read" value="1" />
         <nn name="write" value="2" />
         <nn name="trap" value="3" />
         <nn name="inform" value="4" />
      </NamedNumberList>
   </Object>
   <Object name="snmpProxyContextEngineID" oid="1.3.6.1.6.3.14.1.2.1.3" objtype="s" smitype="s" access="rc" typeref="SNMP-FRAMEWORK-MIB:SnmpEngineID" form="column" status="current" />
   <Object name="snmpProxyContextName" oid="1.3.6.1.6.3.14.1.2.1.4" objtype="s" smitype="s" access="rc" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Object name="snmpProxyTargetParamsIn" oid="1.3.6.1.6.3.14.1.2.1.5" objtype="s" smitype="s" access="rc" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Object name="snmpProxySingleTargetOut" oid="1.3.6.1.6.3.14.1.2.1.6" objtype="s" smitype="s" access="rc" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Object name="snmpProxyMultipleTargetOut" oid="1.3.6.1.6.3.14.1.2.1.7" objtype="s" smitype="s" access="rc" typeref="SNMP-TARGET-MIB:SnmpTagValue" form="column" status="current" />
   <Object name="snmpProxyStorageType" oid="1.3.6.1.6.3.14.1.2.1.8" objtype="i" smitype="i" access="rc" defval="nonVolatile" typeref="SNMPv2-TC:StorageType" form="column" status="current" />
   <Object name="snmpProxyRowStatus" oid="1.3.6.1.6.3.14.1.2.1.9" objtype="i" smitype="i" access="rc" typeref="SNMPv2-TC:RowStatus" form="column" status="current" />
   <Oid name="snmpProxyCompliances" oid="1.3.6.1.6.3.14.3.1" />
   <Oid name="snmpProxyGroups" oid="1.3.6.1.6.3.14.3.2" />
   <ModuleCompliance name="snmpProxyCompliance" oid="1.3.6.1.6.3.14.3.1.1" status="current">
      <McModule module="SNMP-TARGET-MIB">
         <MandatoryGroups>
            <GroupRef name="snmpTargetBasicGroup" />
            <GroupRef name="snmpTargetResponseGroup" />
         </MandatoryGroups>
      </McModule>
      <McModule>
         <MandatoryGroups>
            <GroupRef name="snmpProxyGroup" />
         </MandatoryGroups>
      </McModule>
   </ModuleCompliance>
   <ObjectGroup name="snmpProxyGroup" oid="1.3.6.1.6.3.14.3.2.3" status="current">
      <Objects>
         <ObjectRef name="snmpProxyType" />
         <ObjectRef name="snmpProxyContextEngineID" />
         <ObjectRef name="snmpProxyContextName" />
         <ObjectRef name="snmpProxyTargetParamsIn" />
         <ObjectRef name="snmpProxySingleTargetOut" />
         <ObjectRef name="snmpProxyMultipleTargetOut" />
         <ObjectRef name="snmpProxyStorageType" />
         <ObjectRef name="snmpProxyRowStatus" />
      </Objects>
   </ObjectGroup>
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModuleList SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<ModuleList>
   <ModuleRef name="IANAifType-MIB"/>
   <ModuleRef name="IF-MIB"/>
   <ModuleRef name="TCP-MIB"/>
   <ModuleRef name="RFC1155-MIB"/>
   <ModuleRef name="RFC1213-MIB"/>
   <ModuleRef name="SNMPv2-CONF"/>
   <ModuleRef name="SNMPv2-MIB"/>
   <ModuleRef name="SNMPv2-SMI"/>
   <ModuleRef name="SNMPv2-TC"/>
   <ModuleRef name="SNMPv2-TM"/>
   <ModuleRef name="SNMP-FRAMEWORK-MIB"/>
   <ModuleRef name="SNMP-NOTIFICATION-MIB"/>
   <ModuleRef name="SNMP-REPEATER-MIB"/>
   <ModuleRef name="SNMP-TARGET-MIB"/>
   <ModuleRef name="SNMP-USER-BASED-SM-MIB"/>
   <ModuleRef name="SNMP-VIEW-BASED-ACM-MIB"/>
</ModuleList>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/TCP-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="TCP-MIB">
   <Requires />
   <ModuleIdentity name="tcpMIB" oid="1.3.6.1.2.1.49" lastUpdated="9411010000Z">
      <Organization>IETF SNMPv2 Working Group</Organization>
      <ContactInfo>Keith McCloghrie

Postal: Cisco Systems, Inc.
        170 West Tasman Drive
        San Jose, CA  95134-1706
        US

Phone:  +1 408 526 5260
Email:  kzm@cisco.com</ContactInfo>
      <Description>The MIB module for managing TCP implementations.</Description>
   </ModuleIdentity>
   <Oid name="tcp" oid="1.3.6.1.2.1.6" />
   <Object name="tcpRtoAlgorithm" oid="1.3.6.1.2.1.6.1" objtype="i" smitype="i" access="ro" form="scalar" status="current">
      <NamedNumberList>
         <nn name="other" value="1" />
         <nn name="constant" value="2" />
         <nn name="rsre" value="3" />
         <nn name="vanj" value="4" />
      </NamedNumberList>
   </Object>
   <Object name="tcpRtoMin" oid="1.3.6.1.2.1.6.2" objtype="i" smitype="i32" access="ro" form="scalar" status="current" />
   <Object name="tcpRtoMax" oid="1.3.6.1.2.1.6.3" objtype="i" smitype="i32" access="ro" form="scalar" status="current" />
   <Object name="tcpMaxConn" oid="1.3.6.1.2.1.6.4" objtype="i" smitype="i32" access="ro" form="scalar" status="current" />
   <Object name="tcpActiveOpens" oid="1.3.6.1.2.1.6.5" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpPassiveOpens" oid="1.3.6.1.2.1.6.6" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpAttemptFails" oid="1.3.6.1.2.1.6.7" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpEstabResets" oid="1.3.6.1.2.1.6.8" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpCurrEstab" oid="1.3.6.1.2.1.6.9" objtype="g" smitype="g32" access="ro" form="scalar" status="current" />
   <Object name="tcpInSegs" oid="1.3.6.1.2.1.6.10" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpOutSegs" oid="1.3.6.1.2.1.6.11" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpRetransSegs" oid="1.3.6.1.2.1.6.12" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Table name="tcpConnTable" oid="1.3.6.1.2.1.6.13" status="current">
      <Entry name="tcpConnEntry" oid="1.3.6.1.2.1.6.13.1" status="current">
         <Indexes>
            <ObjectRef name="tcpConnLocalAddress" />
            <ObjectRef name="tcpConnLocalPort" />
            <ObjectRef name="tcpConnRemAddress" />
            <ObjectRef name="tcpConnRemPort" />
         </Indexes>
         <Column name="tcpConnState" column="1" objtype="i" />
         <Column name="tcpConnLocalAddress" column="2" objtype="ip" />
         <Column name="tcpConnLocalPort" column="3" objtype="i" />
         <Column name="tcpConnRemAddress" column="4" objtype="ip" />
         <Column name="tcpConnRemPort" column="5" objtype="i" />
      </Entry>
   </Table>
   <Object name="tcpConnEntry" oid="1.3.6.1.2.1.6.13.1" objtype="entry" smitype="entry" access="na" typeref="TCP-MIB:TcpConnEntry" form="entry" status="current" />
   <Type name="TcpConnEntry" type="SEQUENCE" objtype="entry" />
   <Object name="tcpConnState" oid="1.3.6.1.2.1.6.13.1.1" objtype="i" smitype="i" access="rw" form="column" status="current">
      <NamedNumberList>
         <nn name="closed" value="1" />
         <nn name="listen" value="2" />
         <nn name="synSent" value="3" />
         <nn name="synReceived" value="4" />
         <nn name="established" value="5" />
         <nn name="finWait1" value="6" />
         <nn name="finWait2" value="7" />
         <nn name="closeWait" value="8" />
         <nn name="lastAck" value="9" />
         <nn name="closing" value="10" />
         <nn name="timeWait" value="11" />
         <nn name="deleteTCB" value="12" />
      </NamedNumberList>
   </Object>
   <Object name="tcpConnLocalAddress" oid="1.3.6.1.2.1.6.13.1.2" objtype="ip" smitype="ip" access="ro" form="column" status="current" />
   <Object name="tcpConnLocalPort" oid="1.3.6.1.2.1.6.13.1.3" objtype="i" smitype="i" access="ro" form="column" status="current">
      <RangeSpec>
         <RangeItem lower="0" upper="65535" />
      </RangeSpec>
   </Object>
   <Object name="tcpConnRemAddress" oid="1.3.6.1.2.1.6.13.1.4" objtype="ip" smitype="ip" access="ro" form="column" status="current" />
   <Object name="tcpConnRemPort" oid="1.3.6.1.2.1.6.13.1.5" objtype="i" smitype="i" access="ro" form="column" status="current">
      <RangeSpec>
         <RangeItem lower="0" upper="65535" />
      </RangeSpec>
   </Object>
   <Object name="tcpInErrs" oid="1.3.6.1.2.1.6.14" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="tcpOutRsts" oid="1.3.6.1.2.1.6.15" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Oid name="tcpMIBConformance" oid="1.3.6.1.2.1.49.2" />
   <Oid name="tcpMIBCompliances" oid="1.3.6.1.2.1.49.2.1" />
   <Oid name="tcpMIBGroups" oid="1.3.6.1.2.1.49.2.2" />
   <ModuleCompliance name="tcpMIBCompliance" oid="1.3.6.1.2.1.49.2.1.1" status="current">
      <McModule>
         <MandatoryGroups>
            <GroupRef name="tcpGroup" />
         </MandatoryGroups>
      </McModule>
   </ModuleCompliance>
   <ObjectGroup name="tcpGroup" oid="1.3.6.1.2.1.49.2.2.1" status="current">
      <Objects>
         <ObjectRef name="tcpRtoAlgorithm" />
         <ObjectRef name="tcpRtoMin" />
         <ObjectRef name="tcpRtoMax" />
         <ObjectRef name="tcpMaxConn" />
         <ObjectRef name="tcpActiveOpens" />
         <ObjectRef name="tcpPassiveOpens" />
         <ObjectRef name="tcpAttemptFails" />
         <ObjectRef name="tcpEstabResets" />
         <ObjectRef name="tcpCurrEstab" />
         <ObjectRef name="tcpInSegs" />
         <ObjectRef name="tcpOutSegs" />
         <ObjectRef name="tcpRetransSegs" />
         <ObjectRef name="tcpConnState" />
         <ObjectRef name="tcpConnLocalAddress" />
         <ObjectRef name="tcpConnLocalPort" />
         <ObjectRef name="tcpConnRemAddress" />
         <ObjectRef name="tcpConnRemPort" />
         <ObjectRef name="tcpInErrs" />
         <ObjectRef name="tcpOutRsts" />
      </Objects>
   </ObjectGroup>
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMP-USER-BASED-SM-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMP-USER-BASED-SM-MIB">
   <Requires>
      <ModuleRef name="SNMPv2-TC" />
      <ModuleRef name="SNMP-FRAMEWORK-MIB" />
   </Requires>
   <ModuleIdentity name="snmpUsmMIB" oid="1.3.6.1.6.3.15" lastUpdated="9901200000Z">
      <Organization>SNMPv3 Working Group</Organization>
      <ContactInfo>WG-email:   snmpv3@lists.tislabs.com
Subscribe:  majordomo@lists.tislabs.com
            In msg body:  subscribe snmpv3

Chair:      Russ Mundy
            Trusted Information Systems
postal:     3060 Washington Rd
            Glenwood MD 21738
            USA
email:      mundy@tislabs.com
phone:      +1-301-854-6889

Co-editor   Uri Blumenthal

            IBM T. J. Watson Research
postal:     30 Saw Mill River Pkwy,
            Hawthorne, NY 10532
            USA
email:      uri@watson.ibm.com
phone:      +1-914-784-7964

Co-editor:  Bert Wijnen
            IBM T. J. Watson Research
postal:     Schagen 33
            3461 GL Linschoten
            Netherlands
email:      wijnen@vnet.ibm.com
phone:      +31-348-432-794</ContactInfo>
      <Description>The management information definitions for the
SNMP User-based Security Model.</Description>
   </ModuleIdentity>
   <Oid name="usmMIBObjects" oid="1.3.6.1.6.3.15.1" />
   <Oid name="usmMIBConformance" oid="1.3.6.1.6.3.15.2" />
   <Oid name="usmNoAuthProtocol" oid="1.3.6.1.6.3.10.1.1.1" />
   <Oid name="usmHMACMD5AuthProtocol" oid="1.3.6.1.6.3.10.1.1.2" />
   <Oid name="usmHMACSHAAuthProtocol" oid="1.3.6.1.6.3.10.1.1.3" />
   <Oid name="usmNoPrivProtocol" oid="1.3.6.1.6.3.10.1.2.1" />
   <Oid name="usmDESPrivProtocol" oid="1.3.6.1.6.3.10.1.2.2" />
   <Type name="KeyChange" type="OCTET STRING" objtype="s" status="current" />
   <Oid name="usmStats" oid="1.3.6.1.6.3.15.1.1" />
   <Object name="usmStatsUnsupportedSecLevels" oid="1.3.6.1.6.3.15.1.1.1" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="usmStatsNotInTimeWindows" oid="1.3.6.1.6.3.15.1.1.2" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="usmStatsUnknownUserNames" oid="1.3.6.1.6.3.15.1.1.3" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="usmStatsUnknownEngineIDs" oid="1.3.6.1.6.3.15.1.1.4" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="usmStatsWrongDigests" oid="1.3.6.1.6.3.15.1.1.5" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Object name="usmStatsDecryptionErrors" oid="1.3.6.1.6.3.15.1.1.6" objtype="c" smitype="c32" access="ro" form="scalar" status="current" />
   <Oid name="usmUser" oid="1.3.6.1.6.3.15.1.2" />
   <Object name="usmUserSpinLock" oid="1.3.6.1.6.3.15.1.2.1" objtype="i" smitype="i" access="rw" typeref="SNMPv2-TC:TestAndIncr" form="scalar" status="current" />
   <Table name="usmUserTable" oid="1.3.6.1.6.3.15.1.2.2" status="current">
      <Entry name="usmUserEntry" oid="1.3.6.1.6.3.15.1.2.2.1" status="current">
         <Indexes>
            <ObjectRef name="usmUserEngineID" />
            <ObjectRef name="usmUserName" />
         </Indexes>
         <Column name="usmUserEngineID" column="1" objtype="s" />
         <Column name="usmUserName" column="2" objtype="s" />
         <Column name="usmUserSecurityName" column="3" objtype="s" />
         <Column name="usmUserCloneFrom" column="4" objtype="o" />
         <Column name="usmUserAuthProtocol" column="5" objtype="o" />
         <Column name="usmUserAuthKeyChange" column="6" objtype="s" />
         <Column name="usmUserOwnAuthKeyChange" column="7" objtype="s" />
         <Column name="usmUserPrivProtocol" column="8" objtype="o" />
         <Column name="usmUserPrivKeyChange" column="9" objtype="s" />
         <Column name="usmUserOwnPrivKeyChange" column="10" objtype="s" />
         <Column name="usmUserPublic" column="11" objtype="s" />
         <Column name="usmUserStorageType" column="12" objtype="i" />
         <Column name="usmUserStatus" column="13" objtype="i" />
      </Entry>
   </Table>
   <Object name="usmUserEntry" oid="1.3.6.1.6.3.15.1.2.2.1" objtype="entry" smitype="entry" access="na" typeref="SNMP-USER-BASED-SM-MIB:UsmUserEntry" form="entry" status="current" />
   <Type name="UsmUserEntry" type="SEQUENCE" objtype="entry" />
   <Object name="usmUserEngineID" oid="1.3.6.1.6.3.15.1.2.2.1.1" objtype="s" smitype="s" access="na" typeref="SNMP-FRAMEWORK-MIB:SnmpEngineID" form="column" status="current" />
   <Object name="usmUserName" oid="1.3.6.1.6.3.15.1.2.2.1.2" objtype="s" smitype="s" access="na" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="1" upper="32" />
         </RangeSpec>
      </Size>
   </Object>
   <Object name="usmUserSecurityName" oid="1.3.6.1.6.3.15.1.2.2.1.3" objtype="s" smitype="s" access="ro" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Object name="usmUserCloneFrom" oid="1.3.6.1.6.3.15.1.2.2.1.4" objtype="o" smitype="o" access="rc" typeref="SNMPv2-TC:RowPointer" form="column" status="current" />
   <Object name="usmUserAuthProtocol" oid="1.3.6.1.6.3.15.1.2.2.1.5" objtype="o" smitype="o" access="rc" defval="usmNoAuthProtocol" typeref="SNMPv2-TC:AutonomousType" form="column" status="current" />
   <Object name="usmUserAuthKeyChange" oid="1.3.6.1.6.3.15.1.2.2.1.6" objtype="s" smitype="s" access="rc" defval="&apos;&apos;H" typeref="SNMP-USER-BASED-SM-MIB:KeyChange" form="column" status="current" />
   <Object name="usmUserOwnAuthKeyChange" oid="1.3.6.1.6.3.15.1.2.2.1.7" objtype="s" smitype="s" access="rc" defval="&apos;&apos;H" typeref="SNMP-USER-BASED-SM-MIB:KeyChange" form="column" status="current" />
   <Object name="usmUserPrivProtocol" oid="1.3.6.1.6.3.15.1.2.2.1.8" objtype="o" smitype="o" access="rc" defval="usmNoPrivProtocol" typeref="SNMPv2-TC:AutonomousType" form="column" status="current" />
   <Object name="usmUserPrivKeyChange" oid="1.3.6.1.6.3.15.1.2.2.1.9" objtype="s" smitype="s" access="rc" defval="&apos;&apos;H" typeref="SNMP-USER-BASED-SM-MIB:KeyChange" form="column" status="current" />
   <Object name="usmUserOwnPrivKeyChange" oid="1.3.6.1.6.3.15.1.2.2.1.10" objtype="s" smitype="s" access="rc" defval="&apos;&apos;H" typeref="SNMP-USER-BASED-SM-MIB:KeyChange" form="column" status="current" />
   <Object name="usmUserPublic" oid="1.3.6.1.6.3.15.1.2.2.1.11" objtype="s" smitype="s" access="rc" defval="&apos;&apos;H" form="column" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="0" upper="32" />
         </RangeSpec>
      </Size>
   </Object>
   <Object name="usmUserStorageType" oid="1.3.6.1.6.3.15.1.2.2.1.12" objtype="i" smitype="i" access="rc" defval="nonVolatile" typeref="SNMPv2-TC:StorageType" form="column" status="current" />
   <Object name="usmUserStatus" oid="1.3.6.1.6.3.15.1.2.2.1.13" objtype="i" smitype="i" access="rc" typeref="SNMPv2-TC:RowStatus" form="column" status="current" />
   <Oid name="usmMIBCompliances" oid="1.3.6.1.6.3.15.2.1" />
   <Oid name="usmMIBGroups" oid="1.3.6.1.6.3.15.2.2" />
   <ModuleCompliance name="usmMIBCompliance" oid="1.3.6.1.6.3.15.2.1.1" status="current">
      <McModule>
         <MandatoryGroups>
            <GroupRef name="usmMIBBasicGroup" />
         </MandatoryGroups>
         <McObject name="usmUserAuthProtocol" oid="1.3.6.1.6.3.15.1.2.2.1.5" access="ro" />
         <McObject name="usmUserPrivProtocol" oid="1.3.6.1.6.3.15.1.2.2.1.8" access="ro" />
      </McModule>
   </ModuleCompliance>
   <ObjectGroup name="usmMIBBasicGroup" oid="1.3.6.1.6.3.15.2.2.1" status="current">
      <Objects>
         <ObjectRef name="usmStatsUnsupportedSecLevels" />
         <ObjectRef name="usmStatsNotInTimeWindows" />
         <ObjectRef name="usmStatsUnknownUserNames" />
         <ObjectRef name="usmStatsUnknownEngineIDs" />
         <ObjectRef name="usmStatsWrongDigests" />
         <ObjectRef name="usmStatsDecryptionErrors" />
         <ObjectRef name="usmUserSpinLock" />
         <ObjectRef name="usmUserSecurityName" />
         <ObjectRef name="usmUserCloneFrom" />
         <ObjectRef name="usmUserAuthProtocol" />
         <ObjectRef name="usmUserAuthKeyChange" />
         <ObjectRef name="usmUserOwnAuthKeyChange" />
         <ObjectRef name="usmUserPrivProtocol" />
         <ObjectRef name="usmUserPrivKeyChange" />
         <ObjectRef name="usmUserOwnPrivKeyChange" />
         <ObjectRef name="usmUserPublic" />
         <ObjectRef name="usmUserStorageType" />
         <ObjectRef name="usmUserStatus" />
      </Objects>
   </ObjectGroup>
</Module>
