=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/dtd/snmpMetadata.dtd
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!-- Copyright (c) Monfox, LLC 1999-2003. All Rights Reserved.     -->
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!ELEMENT SnmpMetadata (Module|ModuleRef)*>
<!ATTLIST SnmpMetadata name CDATA "MIB-DATA">

<!ELEMENT Module (Requires?, (ModuleIdentity?|Oid?|Object?|Table?|Notification?|ObjectGroup?|NotificationGroup?|Trap?|Type?|AgentCapabilities?|ModuleCompliance)*)>
<!ATTLIST Module name CDATA "DEFAULT">

<!ELEMENT Requires (ModuleRef*)>

<!ELEMENT ModuleList (ModuleRef*)>

<!ELEMENT ModuleRef EMPTY>
<!ATTLIST ModuleRef name CDATA #REQUIRED>

<!ELEMENT ModuleIdentity (Organization?, ContactInfo?, Description?)>
<!ATTLIST ModuleIdentity name        CDATA #REQUIRED
                         oid         CDATA #REQUIRED
			 lastUpdated CDATA #IMPLIED>

<!ELEMENT Organization (#PCDATA)>
<!ELEMENT Description  (#PCDATA)>
<!ELEMENT ContactInfo  (#PCDATA)>

<!ELEMENT Oid EMPTY>
<!ATTLIST Oid name CDATA #REQUIRED
              oid  CDATA #REQUIRED
	      rawValue CDATA #IMPLIED    
	      >
<!-- NOTE: 'rawValue' used in richMode only -->

<!ELEMENT Table (Entry,Description?)>
<!ATTLIST Table name    CDATA #REQUIRED
                oid     CDATA #REQUIRED
		status ( mandatory|current|obsolete
		        |deprecated|optional) "current">

<!ELEMENT Entry ((Indexes|Augments)?,Column+,Description?)>
<!ATTLIST Entry name   CDATA   #REQUIRED
                oid    CDATA   #REQUIRED
		status ( mandatory|current|obsolete
		        |deprecated|optional) "current">

<!ELEMENT Column EMPTY >
<!ATTLIST Column name    CDATA #REQUIRED
                 column  CDATA #REQUIRED
                 objtype (ip|i|g|c|c64|op|o|t|s|n) #REQUIRED>

<!ELEMENT Indexes (ObjectRef*) >
<!ELEMENT Augments (ObjectRef) >

<!ELEMENT Object ( (NamedNumberList?|Size?|RangeSpec?),Description?) >
<!ATTLIST Object  
	  name CDATA #REQUIRED
	  oid  CDATA #REQUIRED
	  objtype (ip|i|g|c|c64|op|o|t|s|n|entry) #REQUIRED
	  smitype (s|i|i32|u32|c|c32|c64|g|g32|ip|t|op|o|b|entry) #REQUIRED
	  access (ro|rw|wo|rc|na|no|ni) #REQUIRED
	  typeref CDATA #IMPLIED
	  status ( mandatory|current|obsolete|deprecated|optional) "current"
	  defval CDATA #IMPLIED
	  form   (entry|column|scalar) #IMPLIED
	  >

<!ELEMENT ObjectRef EMPTY>
<!ATTLIST ObjectRef 
          name     CDATA #REQUIRED
          modifier (implied) #IMPLIED
	  oid      CDATA #IMPLIED                           
	  objtype  (ip|i|g|c|c64|op|o|t|s|n|entry) #IMPLIED 
	  smitype  (s|i|i32|u32|c|c32|c64|
	            g|g32|ip|t|op|o|b|entry) #IMPLIED
	  >

<!-- NOTE: 'oid' used in richMode only -->
<!-- NOTE: 'objtype' used in richMode only -->
<!-- NOTE: 'smitype' used in richMode only -->

<!ELEMENT Objects (ObjectRef*)>

<!ELEMENT ObjectGroup (Objects,Description?)>
<!ATTLIST ObjectGroup name   CDATA #REQUIRED
                      oid    CDATA #REQUIRED
		      status ( mandatory|current|obsolete
			      |deprecated|optional) "current">

<!ELEMENT Trap (Variables,Description?)>
<!ATTLIST Trap name CDATA #REQUIRED
               enterprise     CDATA #REQUIRED
               oid            CDATA #IMPLIED
	       id             CDATA #REQUIRED
	       status        (  mandatory|current|obsolete
			       |deprecated|optional) "current">
<!ELEMENT Variables (ObjectRef*)>

<!ELEMENT Notification (Objects,Description?)>
<!ATTLIST Notification name   CDATA #REQUIRED
                       oid    CDATA #REQUIRED
		       status ( mandatory|current|obsolete
			       |deprecated|optional) "current">


<!ELEMENT NotificationRef EMPTY>
<!ATTLIST NotificationRef name CDATA #REQUIRED
                          oid    CDATA #IMPLIED
			  >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT Notifications (NotificationRef*)>

<!ELEMENT NotificationGroup (Notifications,Description?) >
<!ATTLIST NotificationGroup name   CDATA #REQUIRED
                            oid    CDATA #REQUIRED
			    status ( mandatory|current|obsolete
	                            |deprecated|optional) "current">

<!ELEMENT Type ( (NamedNumberList?|Size?|RangeSpec?),Description?) >
<!ATTLIST Type name        CDATA #IMPLIED
               type        CDATA #REQUIRED
	       objtype     (ip|i|g|c|c64|op|o|t|s|n|entry) #REQUIRED
               typeref     CDATA #IMPLIED
	       displayHint CDATA #IMPLIED
               status      ( mandatory|current|obsolete
	                    |deprecated|optional) "current" 
	       >

<!ELEMENT Size (RangeSpec)>

<!ELEMENT RangeSpec (RangeItem)*>

<!ELEMENT RangeItem EMPTY>
<!ATTLIST RangeItem  single CDATA #IMPLIED
                     lower  CDATA #IMPLIED
                     upper  CDATA #IMPLIED>

<!ELEMENT NamedNumberList (nn*) >

<!ELEMENT nn EMPTY >
<!ATTLIST nn name   CDATA #REQUIRED
             value  CDATA #REQUIRED>

<!ELEMENT AgentCapabilities (ProductRelease?,Description?,Reference?,Supports*)>
<!ATTLIST AgentCapabilities name CDATA #REQUIRED
			    oid  CDATA #REQUIRED
			    status      ( mandatory|current|obsolete
					 |deprecated|optional) "current">

<!ELEMENT ProductRelease  (#PCDATA)>
<!ELEMENT Reference  (#PCDATA)>

<!ELEMENT Supports  (Includes?,Variation*)>
<!ATTLIST Supports  module CDATA #REQUIRED>

<!ELEMENT Includes  (GroupRef*)>

<!ELEMENT GroupRef EMPTY>
<!ATTLIST GroupRef name CDATA #REQUIRED
                   oid  CDATA #IMPLIED
		   >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT Variation  (Syntax?,WriteSyntax?,CreationRequires?, Description?)>
<!ATTLIST Variation  name CDATA #REQUIRED
                     oid  CDATA #REQUIRED
                     access  CDATA #IMPLIED
                     defval  CDATA #IMPLIED>

<!ELEMENT ModuleCompliance (Description?,Reference?,McModule*)>
<!ATTLIST ModuleCompliance name CDATA #REQUIRED
		           oid  CDATA #REQUIRED
		           status      ( mandatory|current|obsolete
					 |deprecated|optional) "current">

<!ELEMENT McModule (MandatoryGroups?,(McGroup?|McObject?)*)>
<!ATTLIST McModule module CDATA #IMPLIED>

<!ELEMENT MandatoryGroups (GroupRef*)>

<!ELEMENT McGroup (Description?)>
<!ATTLIST McGroup name CDATA #REQUIRED
                  oid  CDATA #IMPLIED
		  >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT McObject (Syntax?,WriteSyntax?,Description?)>
<!ATTLIST McObject  name CDATA #REQUIRED
                    oid  CDATA #REQUIRED
                    access  CDATA #IMPLIED>
                           

<!ELEMENT Syntax (Type)>
<!ELEMENT WriteSyntax (Type)>
<!ELEMENT CreationRequires (ObjectRef*)>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/RFC1155-SMI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:12:04 EDT 2017]-->
<Module name="RFC1155-SMI">
   <Requires />
   <Oid name="ccitt" oid="0" />
   <Oid name="null" oid="0.0" />
   <Oid name="iso" oid="1" />
   <Oid name="org" oid="1.3" />
   <Oid name="dod" oid="1.3.6" />
   <Oid name="internet" oid="1.3.6.1" />
   <Oid name="directory" oid="1.3.6.1.1" />
   <Oid name="mgmt" oid="1.3.6.1.2" />
   <Oid name="experimental" oid="1.3.6.1.3" />
   <Oid name="private" oid="1.3.6.1.4" />
   <Oid name="enterprises" oid="1.3.6.1.4.1" />
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/DSNMP-AGENT-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="DSNMP-AGENT-MIB">
   <Requires>
      <ModuleRef name="SNMP-FRAMEWORK-MIB" />
      <ModuleRef name="SNMPv2-TC" />
      <ModuleRef name="SNMP-TARGET-MIB" />
   </Requires>
   <ModuleIdentity name="dsnmpAgentMIB" oid="1.3.6.1.4.1.3817.1.99.1" lastUpdated="0609060000Z">
      <Organization>Monfox, LLC</Organization>
      <ContactInfo>email:   support@monfox.com
Phone:   +1-678-366-3410

Postal:  11795 Northfall Lane, STE 603
  Alpharetta, GA 30004</ContactInfo>
      <Description>This MIB module defines MIB objects which provide
DynamicSNMP specific Agent functionality</Description>
   </ModuleIdentity>
   <Oid name="monfox" oid="1.3.6.1.4.1.3817" />
   <Oid name="dsnmp" oid="1.3.6.1.4.1.3817.1.99" />
   <Oid name="dsnmpAgentMibObjects" oid="1.3.6.1.4.1.3817.1.99.1.1" />
   <Oid name="dsnmpSubtreeProxyConformance" oid="1.3.6.1.4.1.3817.1.99.1.2" />
   <Type name="SubtreeRootOID" type="OBJECT IDENTIFIER" objtype="o" status="current" />
   <Table name="dsnmpSubtreeProxyTable" oid="1.3.6.1.4.1.3817.1.99.1.1.1" status="current">
      <Entry name="dsnmpSubtreeProxyEntry" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1" status="current">
         <Indexes>
            <ObjectRef name="dsnmpSubtreeProxyName" modifier="implied" />
         </Indexes>
         <Column name="dsnmpSubtreeProxyName" column="1" objtype="s" />
         <Column name="dsnmpSubtreeProxyContextName" column="2" objtype="s" />
         <Column name="dsnmpSubtreeProxyRootOid" column="3" objtype="o" />
         <Column name="dsnmpSubtreeProxyTargetOut" column="4" objtype="s" />
         <Column name="dsnmpSubtreeProxyStorageType" column="5" objtype="i" />
         <Column name="dsnmpSubtreeProxyRowStatus" column="6" objtype="i" />
      </Entry>
   </Table>
   <Object name="dsnmpSubtreeProxyEntry" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1" objtype="entry" smitype="entry" access="na" typeref="DSNMP-AGENT-MIB:DSnmpSubtreeProxyTable" form="entry" status="current" />
   <Type name="DSnmpSubtreeProxyTable" type="SEQUENCE" objtype="entry" />
   <Object name="dsnmpSubtreeProxyName" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1.1" objtype="s" smitype="s" access="na" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="1" upper="32" />
         </RangeSpec>
      </Size>
   </Object>
   <Object name="dsnmpSubtreeProxyContextName" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1.2" objtype="s" smitype="s" access="rc" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Object name="dsnmpSubtreeProxyRootOid" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1.3" objtype="o" smitype="o" access="rc" typeref="DSNMP-AGENT-MIB:SubtreeRootOID" form="column" status="current" />
   <Object name="dsnmpSubtreeProxyTargetOut" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1.4" objtype="s" smitype="s" access="rc" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Object name="dsnmpSubtreeProxyStorageType" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1.5" objtype="i" smitype="i" access="rc" defval="nonVolatile" typeref="SNMPv2-TC:StorageType" form="column" status="current" />
   <Object name="dsnmpSubtreeProxyRowStatus" oid="1.3.6.1.4.1.3817.1.99.1.1.1.1.6" objtype="i" smitype="i" access="rc" typeref="SNMPv2-TC:RowStatus" form="column" status="current" />
   <Oid name="dsnmpSubtreeProxyCompliances" oid="1.3.6.1.4.1.3817.1.99.1.2.1" />
   <Oid name="dsnmpSubtreeProxyGroups" oid="1.3.6.1.4.1.3817.1.99.1.2.2" />
   <ModuleCompliance name="dsnmpSubtreeProxyCompliance" oid="1.3.6.1.4.1.3817.1.99.1.2.1.1" status="current">
      <McModule module="SNMP-TARGET-MIB">
         <MandatoryGroups>
            <GroupRef name="snmpTargetBasicGroup" />
            <GroupRef name="snmpTargetResponseGroup" />
         </MandatoryGroups>
      </McModule>
      <McModule>
         <MandatoryGroups>
            <GroupRef name="dsnmpSubtreeProxyGroup" />
         </MandatoryGroups>
      </McModule>
   </ModuleCompliance>
   <ObjectGroup name="dsnmpSubtreeProxyGroup" oid="1.3.6.1.4.1.3817.1.99.1.2.2.3" status="current">
      <Objects>
         <ObjectRef name="dsnmpSubtreeProxyName" />
         <ObjectRef name="dsnmpSubtreeProxyRootOid" />
         <ObjectRef name="dsnmpSubtreeProxyContextName" />
         <ObjectRef name="dsnmpSubtreeProxyTargetOut" />
         <ObjectRef name="dsnmpSubtreeProxyStorageType" />
         <ObjectRef name="dsnmpSubtreeProxyRowStatus" />
      </Objects>
   </ObjectGroup>
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMPv2-TM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMPv2-TM">
   <Requires />
   <Oid name="snmpUDPDomain" oid="1.3.6.1.6.1.1" />
   <Type name="SnmpUDPAddress" type="OCTET STRING" objtype="s" displayHint="1d.1d.1d.1d/2d" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="6" />
         </RangeSpec>
      </Size>
   </Type>
   <Oid name="snmpCLNSDomain" oid="1.3.6.1.6.1.2" />
   <Oid name="snmpCONSDomain" oid="1.3.6.1.6.1.3" />
   <Type name="SnmpOSIAddress" type="OCTET STRING" objtype="s" displayHint="*1x:/1x:" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="1" />
            <RangeItem lower="4" upper="85" />
         </RangeSpec>
      </Size>
   </Type>
   <Oid name="snmpDDPDomain" oid="1.3.6.1.6.1.4" />
   <Type name="SnmpNBPAddress" type="OCTET STRING" objtype="s" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="3" upper="99" />
         </RangeSpec>
      </Size>
   </Type>
   <Oid name="snmpIPXDomain" oid="1.3.6.1.6.1.5" />
   <Type name="SnmpIPXAddress" type="OCTET STRING" objtype="s" displayHint="4x.1x:1x:1x:1x:1x:1x.2d" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="12" />
         </RangeSpec>
      </Size>
   </Type>
   <Oid name="rfc1157Proxy" oid="1.3.6.1.6.2.1" />
   <Oid name="rfc1157Domain" oid="1.3.6.1.6.2.1.1" />
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMP-FRAMEWORK-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMP-FRAMEWORK-MIB">
   <Requires />
   <ModuleIdentity name="snmpFrameworkMIB" oid="1.3.6.1.6.3.10" lastUpdated="9901190000Z">
      <Organization>SNMPv3 Working Group</Organization>
      <ContactInfo>WG-EMail:   snmpv3@tis.com
Subscribe:  majordomo@tis.com
            In message body:  subscribe snmpv3

Chair:      Russ Mundy
            TIS Labs at Network Associates
postal:     3060 Washington Rd
            Glenwood MD 21738
            USA
EMail:      mundy@tis.com
phone:      +1 301-854-6889

Co-editor   Dave Harrington
            Cabletron Systems, Inc.
postal:     Post Office Box 5005
            Mail Stop: Durham
            35 Industrial Way
            Rochester, NH 03867-5005
            USA
EMail:      dbh@ctron.com
phone:      +1 603-337-7357

Co-editor   Randy Presuhn
            BMC Software, Inc.
postal:     965 Stewart Drive
            Sunnyvale, CA 94086
            USA
EMail:      randy_presuhn@bmc.com
phone:      +1 408-616-3100

Co-editor:  Bert Wijnen
            IBM T.J. Watson Research
postal:     Schagen 33
            3461 GL Linschoten

            Netherlands
EMail:      wijnen@vnet.ibm.com
phone:      +31 348-432-794</ContactInfo>
      <Description>The SNMP Management Architecture MIB</Description>
   </ModuleIdentity>
   <Type name="SnmpEngineID" type="OCTET STRING" objtype="s" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="5" upper="32" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="SnmpSecurityModel" type="INTEGER" objtype="i" status="current">
      <RangeSpec>
         <RangeItem lower="0" upper="2147483647" />
      </RangeSpec>
   </Type>
   <Type name="SnmpMessageProcessingModel" type="INTEGER" objtype="i" status="current">
      <RangeSpec>
         <RangeItem lower="0" upper="2147483647" />
      </RangeSpec>
   </Type>
   <Type name="SnmpSecurityLevel" type="INTEGER" objtype="i" status="current">
      <NamedNumberList>
         <nn name="noAuthNoPriv" value="1" />
         <nn name="authNoPriv" value="2" />
         <nn name="authPriv" value="3" />
      </NamedNumberList>
   </Type>
   <Type name="SnmpAdminString" type="OCTET STRING" objtype="s" displayHint="255a" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="0" upper="255" />
         </RangeSpec>
      </Size>
   </Type>
   <Oid name="snmpFrameworkAdmin" oid="1.3.6.1.6.3.10.1" />
   <Oid name="snmpFrameworkMIBObjects" oid="1.3.6.1.6.3.10.2" />
   <Oid name="snmpFrameworkMIBConformance" oid="1.3.6.1.6.3.10.3" />
   <Oid name="snmpEngine" oid="1.3.6.1.6.3.10.2.1" />
   <Object name="snmpEngineID" oid="1.3.6.1.6.3.10.2.1.1" objtype="s" smitype="s" access="ro" typeref="SNMP-FRAMEWORK-MIB:SnmpEngineID" form="scalar" status="current" />
   <Object name="snmpEngineBoots" oid="1.3.6.1.6.3.10.2.1.2" objtype="i" smitype="i" access="ro" form="scalar" status="current">
      <RangeSpec>
         <RangeItem lower="1" upper="2147483647" />
      </RangeSpec>
   </Object>
   <Object name="snmpEngineTime" oid="1.3.6.1.6.3.10.2.1.3" objtype="i" smitype="i" access="ro" form="scalar" status="current">
      <RangeSpec>
         <RangeItem lower="0" upper="2147483647" />
      </RangeSpec>
   </Object>
   <Object name="snmpEngineMaxMessageSize" oid="1.3.6.1.6.3.10.2.1.4" objtype="i" smitype="i" access="ro" form="scalar" status="current">
      <RangeSpec>
         <RangeItem lower="484" upper="2147483647" />
      </RangeSpec>
   </Object>
   <Oid name="snmpAuthProtocols" oid="1.3.6.1.6.3.10.1.1" />
   <Oid name="snmpPrivProtocols" oid="1.3.6.1.6.3.10.1.2" />
   <Oid name="snmpFrameworkMIBCompliances" oid="1.3.6.1.6.3.10.3.1" />
   <Oid name="snmpFrameworkMIBGroups" oid="1.3.6.1.6.3.10.3.2" />
   <ModuleCompliance name="snmpFrameworkMIBCompliance" oid="1.3.6.1.6.3.10.3.1.1" status="current">
      <McModule>
         <MandatoryGroups>
            <GroupRef name="snmpEngineGroup" />
         </MandatoryGroups>
      </McModule>
   </ModuleCompliance>
   <ObjectGroup name="snmpEngineGroup" oid="1.3.6.1.6.3.10.3.2.1" status="current">
      <Objects>
         <ObjectRef name="snmpEngineID" />
         <ObjectRef name="snmpEngineBoots" />
         <ObjectRef name="snmpEngineTime" />
         <ObjectRef name="snmpEngineMaxMessageSize" />
      </Objects>
   </ObjectGroup>
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMPv2-TC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMPv2-TC">
   <Requires />
   <Type name="DisplayString" type="OCTET STRING" objtype="s" displayHint="255a" status="current" />
   <Type name="PhysAddress" type="OCTET STRING" objtype="s" displayHint="1x:" status="current" />
   <Type name="MacAddress" type="OCTET STRING" objtype="s" displayHint="1x:" status="current" />
   <Type name="TruthValue" type="INTEGER" objtype="i" status="current">
      <NamedNumberList>
         <nn name="true" value="1" />
         <nn name="false" value="2" />
      </NamedNumberList>
   </Type>
   <Type name="TestAndIncr" type="INTEGER" objtype="i" status="current" />
   <Type name="AutonomousType" type="OBJECT IDENTIFIER" objtype="o" status="current" />
   <Type name="InstancePointer" type="OBJECT IDENTIFIER" objtype="o" status="obsolete" />
   <Type name="VariablePointer" type="OBJECT IDENTIFIER" objtype="o" status="current" />
   <Type name="RowPointer" type="OBJECT IDENTIFIER" objtype="o" status="current" />
   <Type name="RowStatus" type="INTEGER" objtype="i" status="current">
      <NamedNumberList>
         <nn name="active" value="1" />
         <nn name="notInService" value="2" />
         <nn name="notReady" value="3" />
         <nn name="createAndGo" value="4" />
         <nn name="createAndWait" value="5" />
         <nn name="destroy" value="6" />
      </NamedNumberList>
   </Type>
   <Type name="TimeStamp" type="TimeTicks" objtype="t" status="current" />
   <Type name="TimeInterval" type="INTEGER" objtype="i" status="current" />
   <Type name="DateAndTime" type="OCTET STRING" objtype="s" displayHint="2d-1d-1d,1d:1d:1d.1d,1a1d:1d" status="current" />
   <Type name="StorageType" type="INTEGER" objtype="i" status="current">
      <NamedNumberList>
         <nn name="other" value="1" />
         <nn name="volatile" value="2" />
         <nn name="nonVolatile" value="3" />
         <nn name="permanent" value="4" />
         <nn name="readOnly" value="5" />
      </NamedNumberList>
   </Type>
   <Type name="TDomain" type="OBJECT IDENTIFIER" objtype="o" status="current" />
   <Type name="TAddress" type="OCTET STRING" objtype="s" status="current" />
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMPv2-SMI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMPv2-SMI">
   <Requires />
   <Oid name="org" oid="1.3" />
   <Oid name="dod" oid="1.3.6" />
   <Oid name="internet" oid="1.3.6.1" />
   <Oid name="directory" oid="1.3.6.1.1" />
   <Oid name="mgmt" oid="1.3.6.1.2" />
   <Oid name="mib-2" oid="1.3.6.1.2.1" />
   <Oid name="transmission" oid="1.3.6.1.2.1.10" />
   <Oid name="experimental" oid="1.3.6.1.3" />
   <Oid name="private" oid="1.3.6.1.4" />
   <Oid name="enterprises" oid="1.3.6.1.4.1" />
   <Oid name="security" oid="1.3.6.1.5" />
   <Oid name="snmpV2" oid="1.3.6.1.6" />
   <Oid name="snmpDomains" oid="1.3.6.1.6.1" />
   <Oid name="snmpProxys" oid="1.3.6.1.6.2" />
   <Oid name="snmpModules" oid="1.3.6.1.6.3" />
   <Type name="ObjectName" type="OBJECT IDENTIFIER" objtype="o" />
   <Type name="NotificationName" type="OBJECT IDENTIFIER" objtype="o" />
   <Oid name="zeroDotZero" oid="0.0" />
</Module>
