=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/dtd/snmpMetadata.dtd
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!-- Copyright (c) Monfox, LLC 1999-2003. All Rights Reserved.     -->
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

<!ELEMENT SnmpMetadata (Module|ModuleRef)*>
<!ATTLIST SnmpMetadata name CDATA "MIB-DATA">

<!ELEMENT Module (Requires?, (ModuleIdentity?|Oid?|Object?|Table?|Notification?|ObjectGroup?|NotificationGroup?|Trap?|Type?|AgentCapabilities?|ModuleCompliance)*)>
<!ATTLIST Module name CDATA "DEFAULT">

<!ELEMENT Requires (ModuleRef*)>

<!ELEMENT ModuleList (ModuleRef*)>

<!ELEMENT ModuleRef EMPTY>
<!ATTLIST ModuleRef name CDATA #REQUIRED>

<!ELEMENT ModuleIdentity (Organization?, ContactInfo?, Description?)>
<!ATTLIST ModuleIdentity name        CDATA #REQUIRED
                         oid         CDATA #REQUIRED
			 lastUpdated CDATA #IMPLIED>

<!ELEMENT Organization (#PCDATA)>
<!ELEMENT Description  (#PCDATA)>
<!ELEMENT ContactInfo  (#PCDATA)>

<!ELEMENT Oid EMPTY>
<!ATTLIST Oid name CDATA #REQUIRED
              oid  CDATA #REQUIRED
	      rawValue CDATA #IMPLIED    
	      >
<!-- NOTE: 'rawValue' used in richMode only -->

<!ELEMENT Table (Entry,Description?)>
<!ATTLIST Table name    CDATA #REQUIRED
                oid     CDATA #REQUIRED
		status ( mandatory|current|obsolete
		        |deprecated|optional) "current">

<!ELEMENT Entry ((Indexes|Augments)?,Column+,Description?)>
<!ATTLIST Entry name   CDATA   #REQUIRED
                oid    CDATA   #REQUIRED
		status ( mandatory|current|obsolete
		        |deprecated|optional) "current">

<!ELEMENT Column EMPTY >
<!ATTLIST Column name    CDATA #REQUIRED
                 column  CDATA #REQUIRED
                 objtype (ip|i|g|c|c64|op|o|t|s|n) #REQUIRED>

<!ELEMENT Indexes (ObjectRef*) >
<!ELEMENT Augments (ObjectRef) >

<!ELEMENT Object ( (NamedNumberList?|Size?|RangeSpec?),Description?) >
<!ATTLIST Object  
	  name CDATA #REQUIRED
	  oid  CDATA #REQUIRED
	  objtype (ip|i|g|c|c64|op|o|t|s|n|entry) #REQUIRED
	  smitype (s|i|i32|u32|c|c32|c64|g|g32|ip|t|op|o|b|entry) #REQUIRED
	  access (ro|rw|wo|rc|na|no|ni) #REQUIRED
	  typeref CDATA #IMPLIED
	  status ( mandatory|current|obsolete|deprecated|optional) "current"
	  defval CDATA #IMPLIED
	  form   (entry|column|scalar) #IMPLIED
	  >

<!ELEMENT ObjectRef EMPTY>
<!ATTLIST ObjectRef 
          name     CDATA #REQUIRED
          modifier (implied) #IMPLIED
	  oid      CDATA #IMPLIED                           
	  objtype  (ip|i|g|c|c64|op|o|t|s|n|entry) #IMPLIED 
	  smitype  (s|i|i32|u32|c|c32|c64|
	            g|g32|ip|t|op|o|b|entry) #IMPLIED
	  >

<!-- NOTE: 'oid' used in richMode only -->
<!-- NOTE: 'objtype' used in richMode only -->
<!-- NOTE: 'smitype' used in richMode only -->

<!ELEMENT Objects (ObjectRef*)>

<!ELEMENT ObjectGroup (Objects,Description?)>
<!ATTLIST ObjectGroup name   CDATA #REQUIRED
                      oid    CDATA #REQUIRED
		      status ( mandatory|current|obsolete
			      |deprecated|optional) "current">

<!ELEMENT Trap (Variables,Description?)>
<!ATTLIST Trap name CDATA #REQUIRED
               enterprise     CDATA #REQUIRED
               oid            CDATA #IMPLIED
	       id             CDATA #REQUIRED
	       status        (  mandatory|current|obsolete
			       |deprecated|optional) "current">
<!ELEMENT Variables (ObjectRef*)>

<!ELEMENT Notification (Objects,Description?)>
<!ATTLIST Notification name   CDATA #REQUIRED
                       oid    CDATA #REQUIRED
		       status ( mandatory|current|obsolete
			       |deprecated|optional) "current">


<!ELEMENT NotificationRef EMPTY>
<!ATTLIST NotificationRef name CDATA #REQUIRED
                          oid    CDATA #IMPLIED
			  >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT Notifications (NotificationRef*)>

<!ELEMENT NotificationGroup (Notifications,Description?) >
<!ATTLIST NotificationGroup name   CDATA #REQUIRED
                            oid    CDATA #REQUIRED
			    status ( mandatory|current|obsolete
	                            |deprecated|optional) "current">

<!ELEMENT Type ( (NamedNumberList?|Size?|RangeSpec?),Description?) >
<!ATTLIST Type name        CDATA #IMPLIED
               type        CDATA #REQUIRED
	       objtype     (ip|i|g|c|c64|op|o|t|s|n|entry) #REQUIRED
               typeref     CDATA #IMPLIED
	       displayHint CDATA #IMPLIED
               status      ( mandatory|current|obsolete
	                    |deprecated|optional) "current" 
	       >

<!ELEMENT Size (RangeSpec)>

<!ELEMENT RangeSpec (RangeItem)*>

<!ELEMENT RangeItem EMPTY>
<!ATTLIST RangeItem  single CDATA #IMPLIED
                     lower  CDATA #IMPLIED
                     upper  CDATA #IMPLIED>

<!ELEMENT NamedNumberList (nn*) >

<!ELEMENT nn EMPTY >
<!ATTLIST nn name   CDATA #REQUIRED
             value  CDATA #REQUIRED>

<!ELEMENT AgentCapabilities (ProductRelease?,Description?,Reference?,Supports*)>
<!ATTLIST AgentCapabilities name CDATA #REQUIRED
			    oid  CDATA #REQUIRED
			    status      ( mandatory|current|obsolete
					 |deprecated|optional) "current">

<!ELEMENT ProductRelease  (#PCDATA)>
<!ELEMENT Reference  (#PCDATA)>

<!ELEMENT Supports  (Includes?,Variation*)>
<!ATTLIST Supports  module CDATA #REQUIRED>

<!ELEMENT Includes  (GroupRef*)>

<!ELEMENT GroupRef EMPTY>
<!ATTLIST GroupRef name CDATA #REQUIRED
                   oid  CDATA #IMPLIED
		   >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT Variation  (Syntax?,WriteSyntax?,CreationRequires?, Description?)>
<!ATTLIST Variation  name CDATA #REQUIRED
                     oid  CDATA #REQUIRED
                     access  CDATA #IMPLIED
                     defval  CDATA #IMPLIED>

<!ELEMENT ModuleCompliance (Description?,Reference?,McModule*)>
<!ATTLIST ModuleCompliance name CDATA #REQUIRED
		           oid  CDATA #REQUIRED
		           status      ( mandatory|current|obsolete
					 |deprecated|optional) "current">

<!ELEMENT McModule (MandatoryGroups?,(McGroup?|McObject?)*)>
<!ATTLIST McModule module CDATA #IMPLIED>

<!ELEMENT MandatoryGroups (GroupRef*)>

<!ELEMENT McGroup (Description?)>
<!ATTLIST McGroup name CDATA #REQUIRED
                  oid  CDATA #IMPLIED
		  >
<!-- NOTE: 'oid' used in richMode only -->

<!ELEMENT McObject (Syntax?,WriteSyntax?,Description?)>
<!ATTLIST McObject  name CDATA #REQUIRED
                    oid  CDATA #REQUIRED
                    access  CDATA #IMPLIED>
                           

<!ELEMENT Syntax (Type)>
<!ELEMENT WriteSyntax (Type)>
<!ELEMENT CreationRequires (ObjectRef*)>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/IANAifType-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="IANAifType-MIB">
   <Requires />
   <ModuleIdentity name="ianaifType" oid="1.3.6.1.2.1.30" lastUpdated="200101120000Z">
      <Organization>IANA</Organization>
      <ContactInfo>Internet Assigned Numbers Authority

Postal: ICANN
        4676 Admiralty Way, Suite 330
        Marina del Rey, CA 90292

Tel:    +1 310 823 9358
E-Mail: iana@iana.org</ContactInfo>
      <Description>This MIB module defines the IANAifType Textual
Convention, and thus the enumerated values of
the ifType object defined in MIB-II's ifTable.</Description>
   </ModuleIdentity>
   <Type name="IANAifType" type="INTEGER" objtype="i" status="current">
      <NamedNumberList>
         <nn name="other" value="1" />
         <nn name="regular1822" value="2" />
         <nn name="hdh1822" value="3" />
         <nn name="ddnX25" value="4" />
         <nn name="rfc877x25" value="5" />
         <nn name="ethernetCsmacd" value="6" />
         <nn name="iso88023Csmacd" value="7" />
         <nn name="iso88024TokenBus" value="8" />
         <nn name="iso88025TokenRing" value="9" />
         <nn name="iso88026Man" value="10" />
         <nn name="starLan" value="11" />
         <nn name="proteon10Mbit" value="12" />
         <nn name="proteon80Mbit" value="13" />
         <nn name="hyperchannel" value="14" />
         <nn name="fddi" value="15" />
         <nn name="lapb" value="16" />
         <nn name="sdlc" value="17" />
         <nn name="ds1" value="18" />
         <nn name="e1" value="19" />
         <nn name="basicISDN" value="20" />
         <nn name="primaryISDN" value="21" />
         <nn name="propPointToPointSerial" value="22" />
         <nn name="ppp" value="23" />
         <nn name="softwareLoopback" value="24" />
         <nn name="eon" value="25" />
         <nn name="ethernet3Mbit" value="26" />
         <nn name="nsip" value="27" />
         <nn name="slip" value="28" />
         <nn name="ultra" value="29" />
         <nn name="ds3" value="30" />
         <nn name="sip" value="31" />
         <nn name="frameRelay" value="32" />
         <nn name="rs232" value="33" />
         <nn name="para" value="34" />
         <nn name="arcnet" value="35" />
         <nn name="arcnetPlus" value="36" />
         <nn name="atm" value="37" />
         <nn name="miox25" value="38" />
         <nn name="sonet" value="39" />
         <nn name="x25ple" value="40" />
         <nn name="iso88022llc" value="41" />
         <nn name="localTalk" value="42" />
         <nn name="smdsDxi" value="43" />
         <nn name="frameRelayService" value="44" />
         <nn name="v35" value="45" />
         <nn name="hssi" value="46" />
         <nn name="hippi" value="47" />
         <nn name="modem" value="48" />
         <nn name="aal5" value="49" />
         <nn name="sonetPath" value="50" />
         <nn name="sonetVT" value="51" />
         <nn name="smdsIcip" value="52" />
         <nn name="propVirtual" value="53" />
         <nn name="propMultiplexor" value="54" />
         <nn name="ieee80212" value="55" />
         <nn name="fibreChannel" value="56" />
         <nn name="hippiInterface" value="57" />
         <nn name="frameRelayInterconnect" value="58" />
         <nn name="aflane8023" value="59" />
         <nn name="aflane8025" value="60" />
         <nn name="cctEmul" value="61" />
         <nn name="fastEther" value="62" />
         <nn name="isdn" value="63" />
         <nn name="v11" value="64" />
         <nn name="v36" value="65" />
         <nn name="g703at64k" value="66" />
         <nn name="g703at2mb" value="67" />
         <nn name="qllc" value="68" />
         <nn name="fastEtherFX" value="69" />
         <nn name="channel" value="70" />
         <nn name="ieee80211" value="71" />
         <nn name="ibm370parChan" value="72" />
         <nn name="escon" value="73" />
         <nn name="dlsw" value="74" />
         <nn name="isdns" value="75" />
         <nn name="isdnu" value="76" />
         <nn name="lapd" value="77" />
         <nn name="ipSwitch" value="78" />
         <nn name="rsrb" value="79" />
         <nn name="atmLogical" value="80" />
         <nn name="ds0" value="81" />
         <nn name="ds0Bundle" value="82" />
         <nn name="bsc" value="83" />
         <nn name="async" value="84" />
         <nn name="cnr" value="85" />
         <nn name="iso88025Dtr" value="86" />
         <nn name="eplrs" value="87" />
         <nn name="arap" value="88" />
         <nn name="propCnls" value="89" />
         <nn name="hostPad" value="90" />
         <nn name="termPad" value="91" />
         <nn name="frameRelayMPI" value="92" />
         <nn name="x213" value="93" />
         <nn name="adsl" value="94" />
         <nn name="radsl" value="95" />
         <nn name="sdsl" value="96" />
         <nn name="vdsl" value="97" />
         <nn name="iso88025CRFPInt" value="98" />
         <nn name="myrinet" value="99" />
         <nn name="voiceEM" value="100" />
         <nn name="voiceFXO" value="101" />
         <nn name="voiceFXS" value="102" />
         <nn name="voiceEncap" value="103" />
         <nn name="voiceOverIp" value="104" />
         <nn name="atmDxi" value="105" />
         <nn name="atmFuni" value="106" />
         <nn name="atmIma" value="107" />
         <nn name="pppMultilinkBundle" value="108" />
         <nn name="ipOverCdlc" value="109" />
         <nn name="ipOverClaw" value="110" />
         <nn name="stackToStack" value="111" />
         <nn name="virtualIpAddress" value="112" />
         <nn name="mpc" value="113" />
         <nn name="ipOverAtm" value="114" />
         <nn name="iso88025Fiber" value="115" />
         <nn name="tdlc" value="116" />
         <nn name="gigabitEthernet" value="117" />
         <nn name="hdlc" value="118" />
         <nn name="lapf" value="119" />
         <nn name="v37" value="120" />
         <nn name="x25mlp" value="121" />
         <nn name="x25huntGroup" value="122" />
         <nn name="trasnpHdlc" value="123" />
         <nn name="interleave" value="124" />
         <nn name="fast" value="125" />
         <nn name="ip" value="126" />
         <nn name="docsCableMaclayer" value="127" />
         <nn name="docsCableDownstream" value="128" />
         <nn name="docsCableUpstream" value="129" />
         <nn name="a12MppSwitch" value="130" />
         <nn name="tunnel" value="131" />
         <nn name="coffee" value="132" />
         <nn name="ces" value="133" />
         <nn name="atmSubInterface" value="134" />
         <nn name="l2vlan" value="135" />
         <nn name="l3ipvlan" value="136" />
         <nn name="l3ipxvlan" value="137" />
         <nn name="digitalPowerline" value="138" />
         <nn name="mediaMailOverIp" value="139" />
         <nn name="dtm" value="140" />
         <nn name="dcn" value="141" />
         <nn name="ipForward" value="142" />
         <nn name="msdsl" value="143" />
         <nn name="ieee1394" value="144" />
         <nn name="if-gsn" value="145" />
         <nn name="dvbRccMacLayer" value="146" />
         <nn name="dvbRccDownstream" value="147" />
         <nn name="dvbRccUpstream" value="148" />
         <nn name="atmVirtual" value="149" />
         <nn name="mplsTunnel" value="150" />
         <nn name="srp" value="151" />
         <nn name="voiceOverAtm" value="152" />
         <nn name="voiceOverFrameRelay" value="153" />
         <nn name="idsl" value="154" />
         <nn name="compositeLink" value="155" />
         <nn name="ss7SigLink" value="156" />
         <nn name="propWirelessP2P" value="157" />
         <nn name="frForward" value="158" />
         <nn name="rfc1483" value="159" />
         <nn name="usb" value="160" />
         <nn name="ieee8023adLag" value="161" />
         <nn name="bgppolicyaccounting" value="162" />
         <nn name="frf16MfrBundle" value="163" />
         <nn name="h323Gatekeeper" value="164" />
         <nn name="h323Proxy" value="165" />
         <nn name="mpls" value="166" />
         <nn name="mfSigLink" value="167" />
         <nn name="hdsl2" value="168" />
         <nn name="shdsl" value="169" />
         <nn name="ds1FDL" value="170" />
         <nn name="pos" value="171" />
         <nn name="dvbAsiln" value="172" />
         <nn name="dvbAsiOut" value="173" />
         <nn name="plc" value="174" />
         <nn name="nfas" value="175" />
         <nn name="tr008" value="176" />
         <nn name="gr303RDT" value="177" />
         <nn name="gr303IDT" value="178" />
         <nn name="isup" value="179" />
         <nn name="propDocsWirelessMaclayer" value="180" />
         <nn name="propDocsWirelessDownstream" value="181" />
         <nn name="propDocsWirelessUpstream" value="182" />
         <nn name="hiperlan2" value="183" />
         <nn name="propBWAp2Mp" value="184" />
         <nn name="sonetOverheadChannel" value="185" />
         <nn name="digitalWrapperOverheadChannel" value="186" />
         <nn name="aal2" value="187" />
         <nn name="radioMAC" value="188" />
         <nn name="atmRadio" value="189" />
         <nn name="imt" value="190" />
         <nn name="mvl" value="191" />
         <nn name="reachDSL" value="192" />
         <nn name="frDlciEndPt" value="193" />
         <nn name="atmVciEndPt" value="194" />
         <nn name="opticalChannel" value="195" />
         <nn name="opticalTransport" value="196" />
      </NamedNumberList>
   </Type>
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/SNMP-USM-DH-OBJECTS-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="SNMP-USM-DH-OBJECTS-MIB">
   <Requires>
      <ModuleRef name="SNMP-USER-BASED-SM-MIB" />
      <ModuleRef name="SNMP-FRAMEWORK-MIB" />
   </Requires>
   <ModuleIdentity name="snmpUsmDHObjectsMIB" oid="1.3.6.1.3.101" lastUpdated="200003060000Z">
      <Organization>Excite@Home</Organization>
      <ContactInfo>Author: Mike StJohns
Postal: Excite@Home
        450 Broadway
        Redwood City, CA 94063
Email:  stjohns@corp.home.net
Phone:  +1-650-556-5368</ContactInfo>
      <Description>The management information definitions for providing forward
secrecy for key changes for the usmUserTable, and for providing a
method for 'kickstarting' access to the agent via a Diffie-Helman
key agreement.</Description>
   </ModuleIdentity>
   <Oid name="usmDHKeyObjects" oid="1.3.6.1.3.101.1" />
   <Oid name="usmDHKeyConformance" oid="1.3.6.1.3.101.2" />
   <Type name="DHKeyChange" type="OCTET STRING" objtype="s" status="current" />
   <Oid name="usmDHPublicObjects" oid="1.3.6.1.3.101.1.1" />
   <Object name="usmDHParameters" oid="1.3.6.1.3.101.1.1.1" objtype="s" smitype="s" access="rw" form="scalar" status="current" />
   <Table name="usmDHUserKeyTable" oid="1.3.6.1.3.101.1.1.2" status="current">
      <Entry name="usmDHUserKeyEntry" oid="1.3.6.1.3.101.1.1.2.1" status="current">
         <Augments>
            <ObjectRef name="SNMP-USER-BASED-SM-MIB:usmUserEntry" />
         </Augments>
         <Column name="usmDHUserAuthKeyChange" column="1" objtype="s" />
         <Column name="usmDHUserOwnAuthKeyChange" column="2" objtype="s" />
         <Column name="usmDHUserPrivKeyChange" column="3" objtype="s" />
         <Column name="usmDHUserOwnPrivKeyChange" column="4" objtype="s" />
      </Entry>
   </Table>
   <Object name="usmDHUserKeyEntry" oid="1.3.6.1.3.101.1.1.2.1" objtype="entry" smitype="entry" access="na" typeref="SNMP-USM-DH-OBJECTS-MIB:UsmDHUserKeyEntry" form="entry" status="current" />
   <Type name="UsmDHUserKeyEntry" type="SEQUENCE" objtype="entry" />
   <Object name="usmDHUserAuthKeyChange" oid="1.3.6.1.3.101.1.1.2.1.1" objtype="s" smitype="s" access="rc" typeref="SNMP-USM-DH-OBJECTS-MIB:DHKeyChange" form="column" status="current" />
   <Object name="usmDHUserOwnAuthKeyChange" oid="1.3.6.1.3.101.1.1.2.1.2" objtype="s" smitype="s" access="rc" typeref="SNMP-USM-DH-OBJECTS-MIB:DHKeyChange" form="column" status="current" />
   <Object name="usmDHUserPrivKeyChange" oid="1.3.6.1.3.101.1.1.2.1.3" objtype="s" smitype="s" access="rc" typeref="SNMP-USM-DH-OBJECTS-MIB:DHKeyChange" form="column" status="current" />
   <Object name="usmDHUserOwnPrivKeyChange" oid="1.3.6.1.3.101.1.1.2.1.4" objtype="s" smitype="s" access="rc" typeref="SNMP-USM-DH-OBJECTS-MIB:DHKeyChange" form="column" status="current" />
   <Oid name="usmDHKickstartGroup" oid="1.3.6.1.3.101.1.2" />
   <Table name="usmDHKickstartTable" oid="1.3.6.1.3.101.1.2.1" status="current">
      <Entry name="usmDHKickstartEntry" oid="1.3.6.1.3.101.1.2.1.1" status="current">
         <Indexes>
            <ObjectRef name="usmDHKickstartIndex" />
         </Indexes>
         <Column name="usmDHKickstartIndex" column="1" objtype="i" />
         <Column name="usmDHKickstartMyPublic" column="2" objtype="s" />
         <Column name="usmDHKickstartMgrPublic" column="3" objtype="s" />
         <Column name="usmDHKickstartSecurityName" column="4" objtype="s" />
      </Entry>
   </Table>
   <Object name="usmDHKickstartEntry" oid="1.3.6.1.3.101.1.2.1.1" objtype="entry" smitype="entry" access="na" typeref="SNMP-USM-DH-OBJECTS-MIB:UsmDHKickstartEntry" form="entry" status="current" />
   <Type name="UsmDHKickstartEntry" type="SEQUENCE" objtype="entry" />
   <Object name="usmDHKickstartIndex" oid="1.3.6.1.3.101.1.2.1.1.1" objtype="i" smitype="i32" access="na" form="column" status="current">
      <RangeSpec>
         <RangeItem lower="1" upper="2147483647" />
      </RangeSpec>
   </Object>
   <Object name="usmDHKickstartMyPublic" oid="1.3.6.1.3.101.1.2.1.1.2" objtype="s" smitype="s" access="ro" form="column" status="current" />
   <Object name="usmDHKickstartMgrPublic" oid="1.3.6.1.3.101.1.2.1.1.3" objtype="s" smitype="s" access="ro" form="column" status="current" />
   <Object name="usmDHKickstartSecurityName" oid="1.3.6.1.3.101.1.2.1.1.4" objtype="s" smitype="s" access="ro" typeref="SNMP-FRAMEWORK-MIB:SnmpAdminString" form="column" status="current" />
   <Oid name="usmDHKeyMIBCompliances" oid="1.3.6.1.3.101.2.1" />
   <Oid name="usmDHKeyMIBGroups" oid="1.3.6.1.3.101.2.2" />
   <ModuleCompliance name="usmDHKeyMIBCompliance" oid="1.3.6.1.3.101.2.1.1" status="current">
      <McModule>
         <McGroup name="usmDHKeyMIBBasicGroup" />
         <McGroup name="usmDHKeyParamGroup" />
         <McGroup name="usmDHKeyKickstartGroup" />
         <McObject name="usmDHParameters" oid="1.3.6.1.3.101.1.1.1" access="ro" />
      </McModule>
   </ModuleCompliance>
   <ObjectGroup name="usmDHKeyMIBBasicGroup" oid="1.3.6.1.3.101.2.2.1" status="current">
      <Objects>
         <ObjectRef name="usmDHUserAuthKeyChange" />
         <ObjectRef name="usmDHUserOwnAuthKeyChange" />
         <ObjectRef name="usmDHUserPrivKeyChange" />
         <ObjectRef name="usmDHUserOwnPrivKeyChange" />
      </Objects>
   </ObjectGroup>
   <ObjectGroup name="usmDHKeyParamGroup" oid="1.3.6.1.3.101.2.2.2" status="current">
      <Objects>
         <ObjectRef name="usmDHParameters" />
      </Objects>
   </ObjectGroup>
   <ObjectGroup name="usmDHKeyKickstartGroup" oid="1.3.6.1.3.101.2.2.3" status="current">
      <Objects>
         <ObjectRef name="usmDHKickstartMyPublic" />
         <ObjectRef name="usmDHKickstartMgrPublic" />
         <ObjectRef name="usmDHKickstartSecurityName" />
      </Objects>
   </ObjectGroup>
</Module>

=== threatsource2023Sec/weblogic/monfox.dsnmp.agent.jar/monfox/toolkit/snmp/mibs/base/TRANSPORT-ADDRESS-MIB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Module SYSTEM "http://www.monfox.com/monfox/toolkit/snmp/dtd/snmpMetadata.dtd">
<!--This is an automatically generated file.-->
<!--Do not Edit!-->
<!--[Thu Aug 10 08:11:58 EDT 2017]-->
<Module name="TRANSPORT-ADDRESS-MIB">
   <Requires />
   <ModuleIdentity name="transportAddressMIB" oid="1.3.6.1.2.1.100" lastUpdated="200211010000Z">
      <Organization>IETF Operations and Management Area</Organization>
      <ContactInfo>Juergen Schoenwaelder (Editor)
TU Braunschweig
Bueltenweg 74/75
38106 Braunschweig, Germany
Phone: +49 531 391-3289
EMail: schoenw@ibr.cs.tu-bs.de

Send comments to &lt;mibs@ops.ietf.org&gt;.</ContactInfo>
      <Description>This MIB module provides commonly used transport
address definitions.

Copyright (C) The Internet Society (2002). This version of
this MIB module is part of RFC 3419; see the RFC itself for
full legal notices.</Description>
   </ModuleIdentity>
   <Oid name="transportDomains" oid="1.3.6.1.2.1.100.1" />
   <Oid name="transportDomainUdpIpv4" oid="1.3.6.1.2.1.100.1.1" />
   <Oid name="transportDomainUdpIpv6" oid="1.3.6.1.2.1.100.1.2" />
   <Oid name="transportDomainUdpIpv4z" oid="1.3.6.1.2.1.100.1.3" />
   <Oid name="transportDomainUdpIpv6z" oid="1.3.6.1.2.1.100.1.4" />
   <Oid name="transportDomainTcpIpv4" oid="1.3.6.1.2.1.100.1.5" />
   <Oid name="transportDomainTcpIpv6" oid="1.3.6.1.2.1.100.1.6" />
   <Oid name="transportDomainTcpIpv4z" oid="1.3.6.1.2.1.100.1.7" />
   <Oid name="transportDomainTcpIpv6z" oid="1.3.6.1.2.1.100.1.8" />
   <Oid name="transportDomainSctpIpv4" oid="1.3.6.1.2.1.100.1.9" />
   <Oid name="transportDomainSctpIpv6" oid="1.3.6.1.2.1.100.1.10" />
   <Oid name="transportDomainSctpIpv4z" oid="1.3.6.1.2.1.100.1.11" />
   <Oid name="transportDomainSctpIpv6z" oid="1.3.6.1.2.1.100.1.12" />
   <Oid name="transportDomainLocal" oid="1.3.6.1.2.1.100.1.13" />
   <Oid name="transportDomainUdpDns" oid="1.3.6.1.2.1.100.1.14" />
   <Oid name="transportDomainTcpDns" oid="1.3.6.1.2.1.100.1.15" />
   <Oid name="transportDomainSctpDns" oid="1.3.6.1.2.1.100.1.16" />
   <Type name="TransportDomain" type="OBJECT IDENTIFIER" objtype="o" status="current" />
   <Type name="TransportAddressType" type="INTEGER" objtype="i" status="current">
      <NamedNumberList>
         <nn name="unknown" value="0" />
         <nn name="udpIpv4" value="1" />
         <nn name="udpIpv6" value="2" />
         <nn name="udpIpv4z" value="3" />
         <nn name="udpIpv6z" value="4" />
         <nn name="tcpIpv4" value="5" />
         <nn name="tcpIpv6" value="6" />
         <nn name="tcpIpv4z" value="7" />
         <nn name="tcpIpv6z" value="8" />
         <nn name="sctpIpv4" value="9" />
         <nn name="sctpIpv6" value="10" />
         <nn name="sctpIpv4z" value="11" />
         <nn name="sctpIpv6z" value="12" />
         <nn name="local" value="13" />
         <nn name="udpDns" value="14" />
         <nn name="tcpDns" value="15" />
         <nn name="sctpDns" value="16" />
      </NamedNumberList>
   </Type>
   <Type name="TransportAddress" type="OCTET STRING" objtype="s" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="0" upper="255" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="TransportAddressIPv4" type="OCTET STRING" objtype="s" displayHint="1d.1d.1d.1d:2d" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="6" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="TransportAddressIPv6" type="OCTET STRING" objtype="s" displayHint="0a[2x:2x:2x:2x:2x:2x:2x:2x]0a:2d" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="18" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="TransportAddressIPv4z" type="OCTET STRING" objtype="s" displayHint="1d.1d.1d.1d%4d:2d" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="10" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="TransportAddressIPv6z" type="OCTET STRING" objtype="s" displayHint="0a[2x:2x:2x:2x:2x:2x:2x:2x%4d]0a:2d" status="current">
      <Size>
         <RangeSpec>
            <RangeItem single="22" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="TransportAddressLocal" type="OCTET STRING" objtype="s" displayHint="1a" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="1" upper="255" />
         </RangeSpec>
      </Size>
   </Type>
   <Type name="TransportAddressDns" type="OCTET STRING" objtype="s" displayHint="1a" status="current">
      <Size>
         <RangeSpec>
            <RangeItem lower="1" upper="255" />
         </RangeSpec>
      </Size>
   </Type>
</Module>
